### ISSUE TITLE
No video id found: undefined 

### ISSUE THREAD

**Issue by KingOfTheSlush** [fent/node-ytdl-core#1012]
Sorry to bother, but I've spent about a day and a half tinkering and trying to search documentation for this error:

Error: input stream: No video id found: undefined
    at Object.exports.getVideoID (/Users/brent/Documents/InkaBot/node_modules/ytdl-core/lib/url-utils.js:63:11)
    at Function.exports.<computed> [as getInfo] (/Users/brent/Documents/InkaBot/node_modules/ytdl-core/lib/info.js:476:29)
    at ytdl (/Users/brent/Documents/InkaBot/node_modules/ytdl-core/lib/index.js:19:8)
    at play (/Users/brent/Documents/InkaBot/index.js:134:11)
    at execute (/Users/brent/Documents/InkaBot/index.js:90:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    

Any YouTube url I try to enter into a discord bot I am building I keep getting the same issue. Searching by name is fine and works well, but I'm not too sure how to get links to play the audio. Here is my code:

```
const Discord = require("discord.js");
const { prefix, token } = require("./config.json");
const ytdl = require("ytdl-core");
const yts = require("yt-search");

const client = new Discord.Client();

const queue = new Map();

client.once("ready", () => {
  console.log("Ready");
});

client.once("reconnecting", () => {
  console.log("Reconnecting");
});

client.once("disconnect", () => {
  console.log("Disconnected");
});

client.on("message", async message => {
  if (message.author.bot) return;
  if (!message.content.startsWith(prefix)) return;

  const serverQueue = queue.get(message.guild.id);

  if (message.content.startsWith(`${prefix}play`)) {
    execute(message, serverQueue);
    return;
  } else if (message.content.startsWith(`${prefix}skip`)) {
    skip(message, serverQueue);
    return;
  } else if (message.content.startsWith(`${prefix}stop`)) {
    stop(message, serverQueue);
    return;
  } else {
    message.channel.send("You need to enter a valid command!");
  }
});

async function execute(message, serverQueue) {
  const args = message.content.split(" ");

  const voiceChannel = message.member.voice.channel;
  if (!voiceChannel)
    return message.channel.send(
      "You need to be in a voice channel to play music!"
    );
  const permissions = voiceChannel.permissionsFor(message.client.user);
  if (!permissions.has("CONNECT") || !permissions.has("SPEAK")) {
    return message.channel.send(
      "I need the permissions to join and speak in your voice channel!"
    );
  }

let song;
if (ytdl.validateURL(args[1])) {
    const songInfo = await ytdl.getInfo(args[1]);
    song = {
    title: songInfo.title,
    url: songInfo.video_url
    };
} else {
    const {videos} = await yts(args.slice(1).join(" "));
    if (!videos.length) return message.channel.send("No songs were found!");
    song = {
        title: videos[0].title,
        url: videos[0].url
    };
}

  if (!serverQueue) {
    const queueContruct = {
      textChannel: message.channel,
      voiceChannel: voiceChannel,
      connection: null,
      songs: [],
      volume: 5,
      playing: true
    };

    queue.set(message.guild.id, queueContruct);

    queueContruct.songs.push(song);

    try {
      var connection = await voiceChannel.join();
      queueContruct.connection = connection;
      play(message.guild, queueContruct.songs[0]);
    } catch (err) {
      console.log(err);
      queue.delete(message.guild.id);
      return message.channel.send(err);
    }
  } else {
    serverQueue.songs.push(song);
    return message.channel.send(`${song.title} has been added to the queue!`);
  }
}

function skip(message, serverQueue) {
  if (!message.member.voice.channel)
    return message.channel.send(
      "You have to be in a voice channel to stop the music!"
    );
  if (!serverQueue)
    return message.channel.send("There is no song that I could skip!");
  serverQueue.connection.dispatcher.end();
}

function stop(message, serverQueue) {
  if (!message.member.voice.channel)
    return message.channel.send(
      "You have to be in a voice channel to stop the music!"
    );
    
  if (!serverQueue)
    return message.channel.send("There is no song that I could stop!");
    
  serverQueue.songs = [];
  serverQueue.connection.dispatcher.end();
}

function play(guild, song) {
  const serverQueue = queue.get(guild.id);
  if (!song) {
    serverQueue.voiceChannel.leave();
    queue.delete(guild.id);
    return;
  }

  const dispatcher = serverQueue.connection
    .play(ytdl(song.url))
    .on("finish", () => {
      serverQueue.songs.shift();
      play(guild, serverQueue.songs[0]);
    })
    .on("error", error => console.error(error));
  dispatcher.setVolumeLogarithmic(serverQueue.volume / 5);
  serverQueue.textChannel.send(`Start playing: **${song.title}**`);
}

client.login(token);
```

Some help would be greatly appreciated!

**Comment by AkatGabrielGoncalves** [comment]
This is not a issue with ytdl-core.... You are trying to play a undefined video link, this is because you are trying to get the video url from ytdl.getInfo. The property "songInfo.video_url" does not exist, what does exist is "songInfo.videoDetails.video_url".

Remember to always check what you are getting from these asynchronous methods. A simple console.log would solve a lot of problems. To find your problem i had to clone your repository and your bot_token is there for everyone to see, never do that, people could manipulate your server or others servers.

**Comment by KingOfTheSlush** [comment]
Ah word, thanks for the heads up, I did change the bot token before uploading my repo. Thanks for the heads up, i'm still new to JS so the console.log is a big help!
