### ISSUE TITLE
Status code 404 - getting playlists

### ISSUE THREAD

**Issue by Heroj04** [fent/node-ytdl-core#102]
Using getInfo() with a playlist URL returns the following error.
Is this not implemented?

using the youtube-dl package allows this feature to return an array with info of each video.

`
Error: Status code 404
    at ClientRequest.<anonymous> (C:\Users\jackf\Dropbox\Programming\Discord Bots\Neo\node_modules\ytdl-core\lib\request.js:33:18)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
`

**Comment by fent** [comment]
It's not.

But it shouldn't return that error, it should instead say it was not able to find the video ID.

**Comment by Heroj04** [comment]
Oh OK,

Are there any plans to implement this in the future?

And in regards to this specific error, It works frine with no error if I use a video URL.

**Comment by fent** [comment]
No plans.

I'm not sure if this feature belongs in this module. If we include this, why not include getting videos from a user's uploads, a user's liked videos, etc.

There's also file to consider when adding an additional feature. Some use this module on the frontend, there's been [efforts](https://github.com/fent/node-ytdl-core/pull/38) to keep dependencies low.

**Comment by karimsa** [comment]
I'm getting this error when trying to fetch a video, although it was working perfectly yesterday.

Code:

```javascript
var fs = require('fs')
    , ytdl = require('ytdl-core')

ytdl('http://youtube.com/watch?v=CovpoxCXCTw')
  .pipe(fs.createWriteStream('./audio.mp3'))
```

Stack trace:

```
Error: Status code 404
    at ClientRequest.<anonymous> (node_modules/ytdl-core/lib/request.js:33:18)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
```

**Comment by ConnorLinfoot** [comment]
@karimsa Looks like YouTube issues?

**Comment by TimeForANinja** [comment]
@karimsa  Works fine for me... have u updated to the lastest v? could be the problem we had today/yesterday https://github.com/fent/node-ytdl-core/issues/104

**Comment by ConnorLinfoot** [comment]
@TimeForANinja Yeah that worked for me :)

**Comment by karimsa** [comment]
Yup, upgrading from `0.7.23` to `0.7.24` worked for me.

**Comment by javalsai** [comment]
> Getting this error...
> can someone help?
> 
> ```
> MinigetError: Status code: 404
>     at ClientRequest.<anonymous> (...\node_modules\miniget\dist\index.js:211:27)
> ```

There's a quick fix in https://github.com/fent/node-ytdl-core/issues/939 , but getting some info return errors, `null`, `undefined`...

**Comment by manhbi18112005** [comment]
> Getting this error...
> can someone help?
> 
> ```
> MinigetError: Status code: 404
>     at ClientRequest.<anonymous> (...\node_modules\miniget\dist\index.js:211:27)
> ```

I'm also having this error, it's could be Youtube's fault. Since 5 hours ago, the modules still work perfectly.

**Comment by TimeForANinja** [comment]
@myselfdsk @javalsai @manhbi18112005 pls keep the discussion in the mentioned #939
