### ISSUE TITLE
Error: Input stream error: Status code: 403

### ISSUE THREAD

**Issue by Sordinni** [fent/node-ytdl-core#1030]
Error: Input stream error: Status code: 403
    at PassThrough.<anonymous> (C:\Users\merll\SordMUSIC\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (events.js:327:22)
    at PassThrough.emit (events.js:315:20)
    at ClientRequest.<anonymous> (C:\Users\merll\SordMUSIC\node_modules\miniget\src\index.ts:238:18)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
[ERROR] 22:11:39 Error: Input stream error: Status code: 403

**Comment by TimeForANinja** [comment]
should be closed with #1022
