### ISSUE TITLE
UnrecoverableError passes validation and catch doesn't catch

### ISSUE THREAD

**Issue by dafatov** [fent/node-ytdl-core#1031]
This error is a logical consequence of an attempt to access a private video, but how to handle this error?
The error passes through validation and is triggered in getBasicInfo. At the same time, catch() does not catch the error.

How to catch or avoid this error without losing functionality?

My part of the code:
```javascript
if (validateURL(audio)) {
    ytdl.getBasicInfo(audio).then(async i => {
        await playUrl(interaction, i);
        await playPlayer(interaction);
    }).catch(err => {throw err})
}
```

Error trace:
```
D:\YandexDisk\MyProjects\Js\Discord\DeusBot\node_modules\ytdl-core\lib\info.js:101
    return new UnrecoverableError(playability.reason || (playability.messages && playability.messages[0]));
           ^

UnrecoverableError: This is a private video. Please sign in to verify that you may see it.
    at privateVideoError (D:\YandexDisk\MyProjects\Js\Discord\DeusBot\node_modules\ytdl-core\lib\info.js:101:12)
    at validate (D:\YandexDisk\MyProjects\Js\Discord\DeusBot\node_modules\ytdl-core\lib\info.js:55:22)
    at pipeline (D:\YandexDisk\MyProjects\Js\Discord\DeusBot\node_modules\ytdl-core\lib\info.js:176:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by TimeForANinja** [comment]
dup of #1002
