### ISSUE TITLE
I want a solution to the age limit that does not include login.

### ISSUE THREAD

**Issue by pixel24287** [fent/node-ytdl-core#1053]
I got this error after a while:

MinigetError: Status code: 410
    at ClientRequest.<anonymous> (C:\Users\joho2\Desktop\next js\youtube downloader\api\node_modules\miniget\dist\index.js:206:27)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:376:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10) {
  statusCode: 410
}

I want a solution to the age limit that does not include login.

URL : https://www.youtube.com/watch?v=QiJcFqQgoAg

**Comment by TimeForANinja** [comment]
don't know of any method atm

**Comment by TimeForANinja** [comment]
closing as dup of #1009
