### ISSUE TITLE
Error with getInfo 

### ISSUE THREAD

**Issue by arajajyothibabu** [fent/node-ytdl-core#106]
```
Error: connect ECONNREFUSED 127.0.0.1:80
at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }
```

Where I'm doing wrong? It worked until yesterday. But don't know why It's raising this error while getting Info of YouTube video. Any help in this issue will be appreciated. Thank you.

**Comment by fent** [comment]
Related to #104 

Fix was just pushed a minute ago, please pull latest.
