### ISSUE TITLE
[QUESTION] Anyway that i can use my cookies.json?

### ISSUE THREAD

**Issue by ItzMiracleOwO** [fent/node-ytdl-core#1067]
Hi, I am having issue working with youtube-dl.
I generated a cookie.json using puppeteer, here it is:
```json
[
  {
    "name": "__Secure-3PSIDCC",
    "value": "AJi4QfHk5BGzuhcL6wwsR4rkMKHY8T-8ed6RRHlleaftz_KyuTy0gjHqbNAvGNBwDHTJ6Td2Ug",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1677034763.702467,
    "size": 90,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "SIDCC",
    "value": "AJi4QfEyGCzenhPOiv-mZhF2zLR4B2vMaSNfka-Xy2I8T5adMCPOa9zhwAe5A_8KpGozqF8",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1677034763.702389,
    "size": 76,
    "httpOnly": false,
    "secure": false,
    "session": false,
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "PREF",
    "value": "f4=4000000&tz=Asia.Hong_Kong&f6=40000000",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570763,
    "size": 44,
    "httpOnly": false,
    "secure": true,
    "session": false,
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "VISITOR_INFO1_LIVE",
    "value": "QsINbnbeoHo",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1661050758.636999,
    "size": 29,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "LOGIN_INFO",
    "value": "AFmmF2swRAIgPo8-8CwPJw-o7DTS8whsU2Tv3QCeZvCxmF973qMv8bACIBMt58QZ0Kr-YxutuGLXvOjbExC_3Zfs3SVqx4RAlsBB:QUQ3MjNmeFVPemE4UHlaOFJLYTNnWi1iMmdpeC1DMk5yY0lMaDAzWUpZUlJPRzM1S0k0anJQbE5YRXBoX0o2UjFidlNQZDVPLVVsQkQyMjFUa0pMaEdUS1BPNktPSk9zemtjWDlsalhRd01nd09GcHBSWHczeUw2RzlTZE5HaTBUSVJ6cjhjWHBIM0JQVHJUbmh4dzF1SkJTYTU3b1RiUlZn",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.636947,
    "size": 327,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "__Secure-3PAPISID",
    "value": "rk0j1iy2Gl46jqJC/A_UwWkjEhkmEtO5b1",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.281728,
    "size": 51,
    "httpOnly": false,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "__Secure-1PAPISID",
    "value": "rk0j1iy2Gl46jqJC/A_UwWkjEhkmEtO5b1",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.281713,
    "size": 51,
    "httpOnly": false,
    "secure": true,
    "session": false,
    "sameParty": true,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "__Secure-1PSID",
    "value": "HQirVgG6MhVc2uwNrIe2xHW7eRg6xcEYHVtErhKDrfpIhM9u0eIeXv9OPNuSFO00LkEywQ.",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.281635,
    "size": 85,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameParty": true,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "SAPISID",
    "value": "rk0j1iy2Gl46jqJC/A_UwWkjEhkmEtO5b1",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.281702,
    "size": 41,
    "httpOnly": false,
    "secure": true,
    "session": false,
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "APISID",
    "value": "EdpDjymK-PUCXgpH/AYzzHJJvkaGXJKWeR",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.281691,
    "size": 40,
    "httpOnly": false,
    "secure": false,
    "session": false,
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "__Secure-3PSID",
    "value": "HQirVgG6MhVc2uwNrIe2xHW7eRg6xcEYHVtErhKDrfpIhM9uim8fS5ED5E-RmEuK9TGWGQ.",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.281654,
    "size": 85,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "SSID",
    "value": "ASIaIF053AAoTxdGq",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.281679,
    "size": 21,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "YSC",
    "value": "3odzNi5-6Uw",
    "domain": ".youtube.com",
    "path": "/",
    "expires": -1,
    "size": 14,
    "httpOnly": true,
    "secure": true,
    "session": true,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "HSID",
    "value": "AnBdN04_Wv2CP9oOZ",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.281668,
    "size": 21,
    "httpOnly": true,
    "secure": false,
    "session": false,
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "SID",
    "value": "HQirVgG6MhVc2uwNrIe2xHW7eRg6xcEYHVtErhKDrfpIhM9uvaqNt0fxkIhBexVncUtk8g.",
    "domain": ".youtube.com",
    "path": "/",
    "expires": 1708570758.281581,
    "size": 74,
    "httpOnly": false,
    "secure": false,
    "session": false,
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  }
]
```

I used this code and included the cookie:
```js
const ytdl = require("ytdl-core")

ytdl("https://www.youtube.com/watch?v=x8VYWazR5mE", {
    requestOptions: {
      headers: {
        Cookie: './cookies.json'
      }
    }
  });
```
And this error popped out:
      throw new UnrecoverableError('Cookie header used in request, but unable to find YouTube identity token');
            ^

UnrecoverableError: Cookie header used in request, but unable to find YouTube identity token
    at C:\Users\simso\Documents\ytcf\node_modules\ytdl-core\lib\info.js:148:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on PassThrough instance at:
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

Why?

**Comment by TimeForANinja** [comment]
watch out sending cookies like this... since they represent you logged in people can impersonate you if they have them...

youtube does not load Cookies from files...
```js
headers: {
        Cookie: './cookies.json'
      }
```
all you do here is set a the Header `Cookie` to the literal string `./cookies.json`...
so you'D have to load the cookies manual and put them as `name: value` pair into the `headers` object

**Comment by ItzMiracleOwO** [comment]
> watch out sending cookies like this... since they represent you logged in people can impersonate you if they have them...
> 
> youtube does not load Cookies from files...
> ```js
> headers: {
>         Cookie: './cookies.json'
>       }
> ```
> all you do here is set a the Header `Cookie` to the literal string `./cookies.json`...
> so you'D have to load the cookies manual and put them as `name: value` pair into the `headers` object

Its a test account So i dont really care
the same error pop out with dat

**Comment by ItzMiracleOwO** [comment]
> watch out sending cookies like this... since they represent you logged in people can impersonate you if they have them...
> 
> youtube does not load Cookies from files...
> ```js
> headers: {
>         Cookie: './cookies.json'
>       }
> ```
> all you do here is set a the Header `Cookie` to the literal string `./cookies.json`...
> so you'D have to load the cookies manual and put them as `name: value` pair into the `headers` object

Oh
So they are the right cookies 🤔

**Comment by TimeForANinja** [comment]
i didn't have a look at the cookies themselfes since (as mentioned) the way you use them is already troublesome

**Comment by ItzMiracleOwO** [comment]
Hmm ok
thanks for the help

**Comment by ItzMiracleOwO** [comment]
```
C:\Users\simso\Documents\ytcf\node_modules\miniget\dist\index.js:206
                let err = new Miniget.MinigetError(`Status code: ${res.statusCode}`, res.statusCode);
                          ^

MinigetError: Status code: 410
    at ClientRequest.<anonymous> (C:\Users\simso\Documents\ytcf\node_modules\miniget\dist\index.js:206:27)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
Emitted 'error' event on PassThrough instance at:
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 410
}
```
Whats this error?

**Comment by ItzMiracleOwO** [comment]
I was using `${name}=${value}` when that error occur

**Comment by ItzMiracleOwO** [comment]
if i use `${name}:${value}` the error would be
```
      throw new UnrecoverableError('Cookie header used in request, but unable to find YouTube identity token');
            ^

UnrecoverableError: Cookie header used in request, but unable to find YouTube identity token
    at C:\Users\simso\Documents\ytcf\node_modules\ytdl-core\lib\info.js:148:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on PassThrough instance at:
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ItzMiracleOwO** [comment]
![image](https://user-images.githubusercontent.com/76854136/155248412-ad910260-0a11-4c32-b403-5835e1d266c6.png)
Heres my cookie, i used:
```js
const cookies = require("./page_cookies.json")

const cookieString = cookies.map(({
    name,
    value
  }) =>
  `${name}:${value}`).join("; ")
console.log(cookieString)

const ytdl = require("ytdl-core")
ytdl("https://www.youtube.com/watch?v=x8VYWazR5mE", {
  requestOptions: {
    headers: {
      Cookie: cookieString
    }
  }
});
```

**Comment by TimeForANinja** [comment]
a) try `cookie` instead of `Cookie`
b) try [this](https://github.com/fent/node-ytdl-core/blob/master/example/cookies.js#L22)

**Comment by ItzMiracleOwO** [comment]
cookie instead of Cookie not working

**Comment by ItzMiracleOwO** [comment]
Also, is there anything wrong with my method of getting the cookies? heres what im doing
```js
                const cookies = await page.cookies();
                var content = await page._client.send('Network.getAllCookies');
                console.log(JSON.stringify(content, null, 4));
                await fs.writeFile('./new_cookies.json', JSON.stringify(content, null, 4));
                await fs.writeFile('./page_cookies.json', JSON.stringify(cookies, null, 4));
```
BOTH new_cookies.json and page_cookies.json not working and i add the id token muanlly

**Comment by TimeForANinja** [comment]
`x-youtube-identity-token` is a header, no cookie

**Comment by ItzMiracleOwO** [comment]
> `x-youtube-identity-token` is a header, no cookie
> 
> and again - if you send all your cookies ppl reading this can impersonate you...

idc cuz its test acc lmao

**Comment by ItzMiracleOwO** [comment]
I got status 410 with the id token
```
C:\Users\simso\Documents\ytcf\node_modules\miniget\dist\index.js:206
                let err = new Miniget.MinigetError(`Status code: ${res.statusCode}`, res.statusCode);
                          ^

MinigetError: Status code: 410
    at ClientRequest.<anonymous> (C:\Users\simso\Documents\ytcf\node_modules\miniget\dist\index.js:206:27)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
Emitted 'error' event on PassThrough instance at:
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 410
}
```

**Comment by ItzMiracleOwO** [comment]
code
```js
const cookies = require("./new_cookies.json")

const cookieString = cookies.cookies.map(({
    name,
    value
  }) =>
  `${name}:${value}`).join("; ")
console.log(cookieString)

const ytdl = require("ytdl-core")
ytdl("https://www.youtube.com/watch?v=x8VYWazR5mE", {
  requestOptions: {
    headers: {
      cookie: cookieString,
      'x-youtube-identity-token': "QUFFLUhqbXZvbjJjLVlWSVJ6ZjhGQ2tFa1FOM19nV2JrZ3w"
    }
  }
});
```

**Comment by ItzMiracleOwO** [comment]
seems that only when i try to fetch a age-restricted video it returns 410
any solutions pls?

**Comment by wolf-yuan-6115** [comment]
> seems that only when i try to fetch a age-restricted video it returns 410
> any solutions pls?

No, age restricted video required login... But I've know some YouTube client on Android called NewPipe. It can fetch age restricted video and play it... Strange

**Comment by ItzMiracleOwO** [comment]
> > seems that only when i try to fetch a age-restricted video it returns 410
> > any solutions pls?
> 
> No, age restricted video required login... But I've know some YouTube client on Android called NewPipe. It can fetch age restricted video and play it... Strange
> 

Alread logged in
the cookies up there are fetched after i login

**Comment by TimeForANinja** [comment]
> I got status 410 with the id token

that's just a problem without a real fix atm 🤷

**Comment by ItzMiracleOwO** [comment]
> > I got status 410 with the id token
> 
> that's just a problem without a real fix atm 🤷 

whats a 'real fix atm' 🤔

**Comment by TimeForANinja** [comment]
there is no reliable way i know of to get rid of 410-errors

**Comment by wolf-yuan-6115** [comment]
> there is no reliable way i know of to get rid of 410-errors

play-dl is better then ytdl now 😐

**Comment by TimeForANinja** [comment]
> play-dl is better then ytdl now 😐

feel free to switch

or feel free to change what's bugging you - in the end it's open source so you can only blame yourself

**Comment by ItzMiracleOwO** [comment]
actully can someone please give me an example code to tell me how to use those cookies and auth tokens and if other stuff is required pls..

**Comment by TimeForANinja** [comment]
your usage [here](https://github.com/fent/node-ytdl-core/issues/1067#issuecomment-1053779791) was correct
it just might not fix all the problems you're having
