### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Can't cut unsupported JSON (no matching closing bracket found)

### ISSUE THREAD

**Issue by JamesBondee** [fent/node-ytdl-core#1144]
Everything worked well, but today i get tihs error:
 at Object.exports.cutAfterJS (/app/node_modules/ytdl-core/lib/utils.js:139:9)
:     at extractNCode (/app/node_modules/ytdl-core/lib/sig.js:65:59)
:     at Object.exports.extractFunctions (/app/node_modules/ytdl-core/lib/sig.js:71:3)
:     at /app/node_modules/ytdl-core/lib/sig.js:18:29
:     at runMicrotasks (<anonymous>)
:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by igor-mytropan** [comment]
Experienced the same issue

**Comment by JamesBondee** [comment]
oh thanks i try
