### ISSUE TITLE
ReferenceError: MC is not defined

### ISSUE THREAD

**Issue by LostAndDead** [fent/node-ytdl-core#1167]
```
ReferenceError: MC is not defined
    at Xua (evalmachine.<anonymous>:1:36)
    at evalmachine.<anonymous>:1:165
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at url (c:\Users\jakem\Desktop\Code\MusicBot\Calliope\node_modules\ytdl-core\lib\sig.js:88:22)
    at Object.exports.setDownloadURL (c:\Users\jakem\Desktop\Code\MusicBot\Calliope\node_modules\ytdl-core\lib\sig.js:100:31)
    at <anonymous> (c:\Users\jakem\Desktop\Code\MusicBot\Calliope\node_modules\ytdl-core\lib\sig.js:118:13)
    at Array.forEach (<anonymous>)
    at Object.exports.decipherFormats (c:\Users\jakem\Desktop\Code\MusicBot\Calliope\node_modules\ytdl-core\lib\sig.js:117:11)
    at runMicrotasks (<anonymous>)
```

The latest version 4.11.2, happens with any song/video requested, I'm unable to trace it to anywhere specific in my code as the error is only within the node modules. Happens every time, and no video is downloaded/streamed. Has been working fine until yesterday with no problems, since yesterday it hasn't worked at all.

**Comment by Xenorio** [comment]
Same here. Just out of the blue, without any changes or even restarts, this shows up.

I would assume something changed on YouTube's side

**Comment by Xenorio** [comment]
@matteopolak Thank you very much, fork works great :)

**Comment by kaddyadriano** [comment]
@matteopolak @LostAndDead Thank you! I was just starting to have the same issue.

**Comment by nextpier** [comment]
Thank you @matteopolak ! It's  working

**Comment by kilianpfr** [comment]
@matteopolak ty so much

**Comment by richardabear** [comment]
Anyone know whats causing this issue? is it an update with youtube? Im not getting the same error but would like to be aware of why that could be happening

**Comment by Pnlvfx** [comment]
Same
