### ISSUE TITLE
Error when opening a Discord Bot with ytdl-core

### ISSUE THREAD

**Issue by MrSouth** [fent/node-ytdl-core#120]
So... I see a Discord Bot with music in JS. The bot need ytdl-core. So, i installed. When i start my bot, this appears in CMD:

C:\Users\Gabriel\Desktop\OhGodMusicBot-master>node server.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'ytdl-core'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Gabriel\Desktop\OhGodMusicBot-master\server.js:2:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

C:\Users\Gabriel\Desktop\OhGodMusicBot-master>PAUSE

**Comment by rectof** [comment]
npm install ytdl-core -g

**Comment by Rainbowdashboygamer** [comment]
const Discord = require('discord.js'); //Require Discord.JS
const client = new Discord.Client(); //Create a new Discord Client
const yt = require ('ytdl-core')

**Comment by Rainbowdashboygamer** [comment]
No video id found: playing `Attention`
    at Object.exports.getURLVideoID (c:\Users\Aaron Tighe\node_modules\ytdl-core\lib\util.js:233:12)
    at Object.exports.getVideoID (c:\Users\Aaron Tighe\node_modules\ytdl-core\lib\util.js:255:20)
    at getInfo (c:\Users\Aaron Tighe\node_modules\ytdl-core\lib\info.js:48:17)
    at ytdl (c:\Users\Aaron Tighe\node_modules\ytdl-core\lib\index.js:19:3)
    at client.on.voiceChannel.join.then.connection (c:\Users\Aaron Tighe\Documents\Sniperbot.js:124:20)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by fent** [comment]
@Rainbowdashboygamer that error is given when you pass an incorrect video id or YouTube url to ytdl-core. In this case, you called ytdl-core with the string "playing \`Attention\`"
