### ISSUE TITLE
Missing catch or finally after try - this error is back in 4.11.4 as well

### ISSUE THREAD

**Issue by arian0gen** [fent/node-ytdl-core#1216]
evalmachine.<anonymous>:24
c[74]),c[64])((0,c[25])(c[24],c[41]),c[35],c[33+Math.pow(8,3)%229],c[92]),c[70])(c[87],c[27])}try{8>=c[92]&&(0,c[15])((0,c[35])(c[36],c[20]),c[11],c[29])}catch(d){(0,c[60])(c[92],c[93])}try{1>c[45]?((0,c[60])(c[2],c[93]),c[60])(c[91],c[93]):((0,c[88])(c[93],c[86]),c[11])(c[57])}catch(d){(0,c[85])((0,c[80])(),c[56],c[0])}};qma(ncode);

                                     ^

SyntaxError: Missing catch or finally after try

**Comment by Kisakay** [comment]
I have the same issue : 
evalmachine.<anonymous>:24
c[74]),c[64])((0,c[25])(c[24],c[41]),c[35],c[33+Math.pow(8,3)%229],c[92]),c[70])(c[87],c[27])}try{8>=c[92]&&(0,c[15])((0,c[35])(c[36],c[20]),c[11],c[29])}catch(d){(0,c[60])(c[92],c[93])}try{1>c[45]?((0,c[60])(c[2],c[93]),c[60])(c[91],c[93]):((0,c[88])(c[93],c[86]),c[11])(c[57])}catch(d){(0,c[85])((0,c[80])(),c[56],c[0])}};qma(ncode);

**Comment by danisty** [comment]
Exact same issue and error as the one mentioned above me.

**Comment by Sansekai** [comment]
provisionally im using https://www.npmjs.com/package/@distube/ytdl-core work for me

Try this:
``"ytdl-core": "npm:@distube/ytdl-core",``

**Comment by ShadowLp174** [comment]
Happened a few hours ago a few times, then it worked again, now it's broken again

**Comment by arian0gen** [comment]
this exact error was 2 weeks ago in 4.11.3 and then we freaked out, and then they fixed and now it is back again, it is probably because youtube keep changing their code so...

**Comment by nukeop** [comment]
This fork uses some custom HTTP client that doesn't play ball when you mock fetch in tests: https://www.npmjs.com/package/undici

It works in practice but it ruins all my test suites.

**Comment by danisty** [comment]
After some research I've found that the problem has to do with the signature deciphering extraction of functions, specifically the `extractNCode` function, when calling [cutAfterJS](https://github.com/fent/node-ytdl-core/blob/0d3f91b424e81aa79fc2ec021d921d4d21f3e6ef/lib/utils.js#L72) it fails to escape the following string `/[/,-33,/,/]{/,function` due to the literal `/` characters inside a RegEx character set, and so it counts opening and closing brackets incorrectly as it treats most part of the code as a regular expression, resulting in the script not getting to the end of the function and missing a catch block and a return statement.

**TEMP FIX**
Add a check for RegEx character sets, replace
https://github.com/fent/node-ytdl-core/blob/0d3f91b424e81aa79fc2ec021d921d4d21f3e6ef/lib/utils.js#L97-L102

for

```js
  // Go through all characters from the start
  for (i = 0; i < mixedJson.length; i++) {
    // End of current escaped object
    if (!isEscaped && isEscapedObject !== null && mixedJson[i] === isEscapedObject.end) {
      // Ignore character inside RegEx character set with a range of 30 characters
      let charsetStart = mixedJson.substring(i - 15, i).search(/\[[^\]]*/)
      let charsetEnd = mixedJson.substring(i, i + 15).search(/[^\[]]*\]/)
      if (mixedJson[i] == '/' && charsetStart !== -1 && charsetEnd !== -1)
        continue;

      isEscapedObject = null;
      continue;
```

You can find the file locally in `./node_modules/ytdl-core/lib/utils.js`

**Comment by dim4ik1106** [comment]
> After some research I've found that the problem has to do with the signature deciphering extraction of functions, specifically the `extractNCode` function, when calling [cutAfterJS](https://github.com/fent/node-ytdl-core/blob/0d3f91b424e81aa79fc2ec021d921d4d21f3e6ef/lib/utils.js#L72) it fails to escape the following string `/[/,-33,/,/]{/,function` due to the literal `/` characters inside a RegEx character set, and so it counts opening and closing brackets incorrectly as it treats most part of the code as a regular expression, resulting in the script not getting to the end of the function and missing a catch block and a return statement.
> 
> **TEMP FIX** Add a check for RegEx character sets, replace
> 
> https://github.com/fent/node-ytdl-core/blob/0d3f91b424e81aa79fc2ec021d921d4d21f3e6ef/lib/utils.js#L97-L102
> 
> with
> 
> ```js
>   // Go through all characters from the start
>   for (i = 0; i < mixedJson.length; i++) {
>     // End of current escaped object
>     if (!isEscaped && isEscapedObject !== null && mixedJson[i] === isEscapedObject.end) {
>       // Ignore character inside RegEx character set with a range of 30 characters
>       let charsetStart = mixedJson.substring(i - 15, i).search(/\[[^\]]*/)
>       let charsetEnd = mixedJson.substring(i, i + 15).search(/[^\[]*\]/)
>       if (mixedJson[i] == '/' && charsetStart !== -1 && charsetEnd !== -1)
>         continue;
> 
>       isEscapedObject = null;
>       continue;
> ```
> 
> You can find the file locally in `./node_modules/ytdl-core/lib/utils.js`

This works for me. I made a patch with this changes, so you can use it with
`"ytdl-core": "git+https://github.com/dim4ik1106/node-ytdl-core.git#master",`

**Comment by khlevon** [comment]
To make your code work you can use this patch
```json
"ytdl-core": "git+ssh://git@github.com:khlevon/node-ytdl-core.git#v4.11.4-patch.1"
```

**Comment by hamirmahal** [comment]
> To make your code work you can use this patch
> 
> ```json
> "ytdl-core": "git+ssh://git@github.com:khlevon/node-ytdl-core.git#v4.11.4-patch.1"
> ```

Is there any reason why this might work locally, but not on an Express.js application deployed to Vercel?

`Unhandled Promise Rejection`
```json
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "SyntaxError: Missing catch or finally after try",
  "reason": {
    "errorType": "SyntaxError",
    "errorMessage": "Missing catch or finally after try",
    "stack": [
      "evalmachine.<anonymous>:24",
      "c[74]),c[64])((0,c[25])(c[24],c[41]),c[35],c[33+Math.pow(8,3)%229],c[92]),c[70])(c[87],c[27])}try{8>=c[92]&&(0,c[15])((0,c[35])(c[36],c[20]),c[11],c[29])}catch(d){(0,c[60])(c[92],c[93])}try{1>c[45]?((0,c[60])(c[2],c[93]),c[60])(c[91],c[93]):((0,c[88])(c[93],c[86]),c[11])(c[57])}catch(d){(0,c[85])((0,c[80])(),c[56],c[0])}};qma(ncode);",
      "                                                                                                                                                                                                                                                                                                                                  ^",
      "",
      "SyntaxError: Missing catch or finally after try",
      "    at new Script (node:vm:100:7)",
      "    at exports.decipherFormats (/var/task/node_modules/ytdl-core/lib/sig.js:116:51)",
      "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at async Promise.all (index 0)",
      "    at async exports.getInfo (/var/task/node_modules/ytdl-core/lib/info.js:401:17)"
    ]
  },
  "promise": {},
  "stack": [
    "Runtime.UnhandledPromiseRejection: SyntaxError: Missing catch or finally after try",
    "    at process.<anonymous> (file:///var/runtime/index.mjs:1189:17)",
    "    at process.emit (node:events:525:35)",
    "    at emit (node:internal/process/promises:149:20)",
    "    at processPromiseRejections (node:internal/process/promises:283:27)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
  ]
}
```
```
Unknown application error occurred
Runtime.Unknown
```

Your suggestion works just fine for me locally. Thanks for posting it!

**Comment by MeLikeApplez** [comment]
UnhandledPromiseRejectionWarning: Error: Could not parse decipher function: TypeError: decipherFuncName.replaceAll is not a function
Apr 27 10:07:58 PM      at extractDecipher (/opt/render/project/src/node_modules/ytdl-core/lib/sig.js:92:13)
Apr 27 10:07:58 PM      at Object.exports.extractFunctions (/opt/render/project/src/node_modules/ytdl-core/lib/sig.js:126:3)
Apr 27 10:07:58 PM      at /opt/render/project/src/node_modules/ytdl-core/lib/sig.js:22:29
Apr 27 10:07:58 PM      at runMicrotasks (<anonymous>)
Apr 27 10:07:58 PM      at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by nezort11** [comment]
> To make your code work you can use this patch
> 
> ```json
> "ytdl-core": "git+ssh://git@github.com:khlevon/node-ytdl-core.git#v4.11.4-patch.1"
> ```

For me this syntax worked:
```json
"ytdl-core": "https://github.com/khlevon/node-ytdl-core.git#v4.11.4-patch.1"
```

**Comment by khlevon** [comment]
> To make your code work you can use this patch
> 
> ```json
> "ytdl-core": "git+ssh://git@github.com:khlevon/node-ytdl-core.git#v4.11.4-patch.1"
> ```
----
In case someone needs to have node 12 and 14 support, you can use this patch 
```json
"ytdl-core": "git+ssh://git@github.com:khlevon/node-ytdl-core.git#v4.11.4-patch.2"
```

For more details check this PR: https://github.com/fent/node-ytdl-core/pull/1217
Also, do not hesitate to review the code and write comments or approve it :)

**Comment by fpsone** [comment]
> @Sansekai
> 
> > provisionally im using https://www.npmjs.com/package/@distube/ytdl-core work for me
> > Try this: `"ytdl-core": "npm:@distube/ytdl-core",`
> 
> Don't forget to add the version number `^4.11.9`
> 
> `"ytdl-core": "npm:@distube/ytdl-core@^4.11.9"`

4.11.9 cannot play some streams, I updated to `4.11.10` and it's working normally

`npm i ytdl-core@npm:@distube/ytdl-core@latest`

**Comment by ledlamp** [comment]
`npm install khlevon/node-ytdl-core.git#v4.11.4-patch.1` work
