### ISSUE TITLE
Getting Network for More Than 2 Minutes Video

### ISSUE THREAD

**Issue by vasu7A** [fent/node-ytdl-core#1235]
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK), 
index.js:1191 Error: Network Error
    at createError (createError.js:16:1)
    at XMLHttpRequest.handleError (xhr.js:91:1)

**Comment by TimeForANinja** [comment]
`Network Error` is usually a problem with your network connection and not library related
