### ISSUE TITLE
ERR_NO_RESULT: Could not extract stream for this track

### ISSUE THREAD

**Issue by Greensky-gs** [fent/node-ytdl-core#1245]
## ERR_NO_RESULT: Could not extract stream for this track

I get this error sometimes when extracting a song. The error is coming from the evalmachine (apparently)
As I never touched the code of ytdl-core, I am just reporting the issue and I don't know how to fix it

### Context

I am making a music bot, using [discord-player](https://github.com/Androz2091/discord-player), and it uses `ytdl-core` when playing songs

### When it happens

It seems to happen randomly, because sometimes it happens on a certain song, and sometimes not. As I don't know how ytdl-core works, I can't tell with more precision the reason why it happens. The only thing I know is that I use a URL to fetch songs, so they stay the same even when the bot restarts, and the error happens, but not everytime

### Error

Here is the error log I got in my cmd

```
ERR_NO_RESULT: Could not extract stream for this track

evalmachine.<anonymous>:23
-198148851,1640174308];c[24]=c;c[48]=c;c[52]=c;try{try{-7>=c[44]&&((0,c[42])((0,c[78])(c[52],c[28]),c[70],(0,c[13])(c[83]),c[55],c[52]),c[27])((0,c[31])(c[83],c[69]),c[65],c[17],c[24]),((0,c[30])(),c[37])(c[68],c[new Date("1970-01-01T08:00:04.000+08:00")/1E3])};hma(ncode);

                                                   ^

SyntaxError: Missing catch or finally after try
    at new Script (node:vm:100:7)
    at exports.decipherFormats (E:\scripts\js\audioli\node_modules\ytdl-core\lib\sig.js:116:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async exports.getInfo (E:\scripts\js\audioli\node_modules\ytdl-core\lib\info.js:401:17)
    at Proxy.<anonymous> (E:\scripts\js\audioli\node_modules\discord-player\dist\index.js:580:25)
    at #throw (E:\scripts\js\audioli\node_modules\discord-player\dist\index.js:1861:80)
    at GuildQueuePlayerNode.play (E:\scripts\js\audioli\node_modules\discord-player\dist\index.js:1806:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by MR-Flame-exe** [comment]
To solve this issue I suggest you to downgrade your ytdl-core to the version [4.11.4](https://www.npmjs.com/package/ytdl-core/v/4.11.4) and wait for a patch, I did this in my case and now everything works fine, hoping to have helped you

Command to use to downgrade in your console:

`npm install ytdl-core@4.11.4`

**Comment by fpsone** [comment]
I changed the extractor and it works well https://github.com/Androz2091/discord-player/issues/1705#issuecomment-1499141602
