### ISSUE TITLE
I am using Contabo Server (Sign in to confirm you’re not a bot)

### ISSUE THREAD

**Issue by apurbapathak** [fent/node-ytdl-core#1314]
My Log:

root@vmi2090944:/www/wwwroot/ytdl-core# node index.js
Error fetching info for first request: UnrecoverableError: Sign in to confirm you’re not a bot
    at exports.playError (/www/wwwroot/ytdl-core/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
    at exports.getBasicInfo (/www/wwwroot/ytdl-core/node_modules/@distube/ytdl-core/lib/info.js:46:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error fetching info for second request: UnrecoverableError: Sign in to confirm you’re not a bot
    at exports.playError (/www/wwwroot/ytdl-core/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
    at exports.getBasicInfo (/www/wwwroot/ytdl-core/node_modules/@distube/ytdl-core/lib/info.js:46:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
root@vmi2090944:/www/wwwroot/ytdl-core# node index.js
Error fetching info for first request: Error: bind EADDRNOTAVAIL 2a02:c206:2209:944::e
    at internalConnect (node:net:1064:18)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:462:18)
    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1381:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
  errno: -99,
  code: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '2a02:c206:2209:944::e'
}
Error fetching info for second request: Error: bind EADDRNOTAVAIL 2a02:c206:2209:944::e
    at internalConnect (node:net:1064:18)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:462:18)
    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1381:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
  errno: -99,
  code: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '2a02:c206:2209:944::e'
}
root@vmi2090944:/www/wwwroot/ytdl-core# node index.js
Error fetching info for first request: UnrecoverableError: Sign in to confirm you’re not a bot
    at exports.playError (/www/wwwroot/ytdl-core/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
    at exports.getBasicInfo (/www/wwwroot/ytdl-core/node_modules/@distube/ytdl-core/lib/info.js:46:25)

**Comment by asenmitrev** [comment]
Seems most cloud priver ips are blocked. I'm looking for a workaround.

yt-dlp seems to work well otherwise
