### ISSUE TITLE
Error: Could not extract functions

### ISSUE THREAD

**Issue by NabiKAZ** [fent/node-ytdl-core#1318]
The code that was working until yesterday suddenly gives this error:

```
C:\Nabi\notpixel\node_modules\ytdl-core\lib\sig.js:20
    throw Error('Could not extract functions');
          ^

Error: Could not extract functions
    at C:\Nabi\notpixel\node_modules\ytdl-core\lib\sig.js:20:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on PassThrough instance at:
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.0
```

**Comment by Dari-Enmanuel-Garcia** [comment]
I have the same problem

**Comment by GuilhermeCanoa** [comment]
same issue here! i guess youtube changed something...

**Comment by planet-bluto** [comment]
That seems like a new bug that's showed up in the package and the general consensus for now seems to be to try the [@distube/ytdl-core](https://www.npmjs.com/package/@distube/ytdl-core) package instead.

You can install it in place of ytdl-core like this
```
npm uninstall ytdl-core && npm i ytdl-core@npm:@distube/ytdl-core
```

**Comment by ghooms** [comment]
planet-bluto's solution worked for me

**Comment by NabiKAZ** [comment]
Of course, the suggested option https://github.com/distubejs/ytdl-core is also good. But I migrated to https://github.com/foxesdocode/yt-dlp-wrap to have a closer connection with the yt-dlp parent program and not get bugs again. It also supports cookies jar file.

**Comment by planet-bluto** [comment]
In my project, I ended up using both- one for getting info (ytdl) and one for fetching audio data (yt-dlp)- so that's a totally valid solution. I don't remember if there was really a way to get metadata with just yt-dlp, but I didn't look into it because I didn't want to completely replace all the instances in which I did use ytdl

**Comment by ahmednabik** [comment]
I was getting this same error but fortunately stumbled upon this thread via search and the forked library worked. Good job to the guy maintaining the fork  (the original ytdl-core hasn't been updated in a year)

**Comment by dharmendra9503** [comment]
I have same problem.

**Comment by dharmendra9503** [comment]
@planet-bluto Solution Worked for me.

**Comment by kumargaf** [comment]
It was able to download mp4 but video is not opening

**Comment by EmilioMaestro** [comment]
Thanks @planet-bluto 

npm i ytdl-core@npm:@distube/ytdl-core 

Solved the problem.

**Comment by nethan-k** [comment]
I am getting a typescript error with @planet-bluto solution.
```File '<path>/node_modules/ytdl-core/typings/index.d.ts' is not a module.```
Does anybody know how I can fix this?

**Comment by Anas12312** [comment]
> I am getting a typescript error with [@planet-bluto](https://github.com/planet-bluto) solution. `File '<path>/node_modules/ytdl-core/typings/index.d.ts' is not a module.` Does anybody know how I can fix this?

Same problem

**Comment by bobby-rust** [comment]
> I am getting a typescript error with [@planet-bluto](https://github.com/planet-bluto) solution. `File '<path>/node_modules/ytdl-core/typings/index.d.ts' is not a module.` Does anybody know how I can fix this?

`npm i @distube/ytdl-core@latest`
and use
`import ytdl from '@distube/ytdl-core';`

**Comment by tbizze** [comment]
> Isso parece ser um novo bug que apareceu no pacote e o consenso geral por enquanto parece ser tentar o pacote [@distube/ytdl-core .](https://www.npmjs.com/package/@distube/ytdl-core)
> 
> Você pode instalá-lo no lugar do ytdl-core assim
> 
> ```
> npm uninstall ytdl-core && npm i ytdl-core@npm:@distube/ytdl-core
> ```

@planet-bluto Thanks for the solution.
I was trying to use it for the first time and had the same error, and this solution worked!

Note: to get the video information on YouTube I had to change the code, as it is in the repository [@distube/ytdl-core](https://github.com/distubejs/ytdl-core)

**Comment by tbizze** [comment]
> That seems like a new bug that's showed up in the package and the general consensus for now seems to be to try the [@distube/ytdl-core](https://www.npmjs.com/package/@distube/ytdl-core) package instead.
> 
> You can install it in place of ytdl-core like this
> 
> ```
> npm uninstall ytdl-core && npm i ytdl-core@npm:@distube/ytdl-core
> ```

@planet-bluto Thanks for the solution.
I was trying to use it for the first time and had the same error, and this solution worked!

**Note:** to get the video information on YouTube I had to change the code, as it is in the repository [@distube/ytdl-core](https://github.com/distubejs/ytdl-core)

**Comment by Ky-Wilson** [comment]
> That seems like a new bug that's showed up in the package and the general consensus for now seems to be to try the [@distube/ytdl-core](https://www.npmjs.com/package/@distube/ytdl-core) package instead.
> 
> You can install it in place of ytdl-core like this
> 
> ```
> npm uninstall ytdl-core && npm i ytdl-core@npm:@distube/ytdl-core
> ```

it's working thk

**Comment by Csasaka19** [comment]
Solution from @planet-bluto  worked fine for me

**Comment by hugohugo130** [comment]
Solution from @planet-bluto  worked fine for me

**Comment by plflanagan** [comment]
> That seems like a new bug that's showed up in the package and the general consensus for now seems to be to try the [@distube/ytdl-core](https://www.npmjs.com/package/@distube/ytdl-core) package instead.
> 
> You can install it in place of ytdl-core like this
> 
> ```
> npm uninstall ytdl-core && npm i ytdl-core@npm:@distube/ytdl-core
> ```

This worked for me!

**Comment by lalitshirsath008** [comment]
@planet-bluto Thanks! its work for me.

**Comment by bileyassein** [comment]
Thanks @planet-bluto it worked

**Comment by AswinKaruppiah** [comment]
Thanks @planet-bluto  Thanks! its work for me.

**Comment by Omarkhodjaev** [comment]
> > I am getting a typescript error with [@planet-bluto](https://github.com/planet-bluto) solution. `File '<path>/node_modules/ytdl-core/typings/index.d.ts' is not a module.` Does anybody know how I can fix this?
> 
> `npm i @distube/ytdl-core@latest` and use `import ytdl from '@distube/ytdl-core';`

Great, this works for me

**Comment by matyas095** [comment]
@planet-bluto's solution works, but only on Windows, on Debian I'm getting this error then:

```
webidl.is.File = webidl.util.MakeTypeAssertion(File)
                                               ^

ReferenceError: File is not defined
    at Object.<anonymous> (.../node_modules/undici/lib/web/webidl/index.js:531:48)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (.../test/node_modules/undici/lib/web/fetch/util.js:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

Node.js v18.20.4
```

**Comment by smarko-web** [comment]
> That seems like a new bug that's showed up in the package and the general consensus for now seems to be to try the [@distube/ytdl-core](https://www.npmjs.com/package/@distube/ytdl-core) package instead.
> 
> You can install it in place of ytdl-core like this
> 
> ```
> npm uninstall ytdl-core && npm i ytdl-core@npm:@distube/ytdl-core
> ```

@planet-bluto,  Does this solution still work with [@distube/ytdl-core](https://www.npmjs.com/package/@distube/ytdl-core) version ```4.16.12```? The last time I tried using it(last week) for downloading media it generated two ```17***-player.js``` files without any successful download.

**Comment by BDT-4248** [comment]
> That seems like a new bug that's showed up in the package and the general consensus for now seems to be to try the [@distube/ytdl-core](https://www.npmjs.com/package/@distube/ytdl-core) package instead.
> 
> You can install it in place of ytdl-core like this
> 
> ```
> npm uninstall ytdl-core && npm i ytdl-core@npm:@distube/ytdl-core
> ```

i get this error: `MinigetError: Status code: 403`
what can i do  now???

**Comment by smarko-web** [comment]
> > That seems like a new bug that's showed up in the package and the general consensus for now seems to be to try the [@distube/ytdl-core](https://www.npmjs.com/package/@distube/ytdl-core) package instead.
> > 
> > You can install it in place of ytdl-core like this
> > 
> > ```
> > npm uninstall ytdl-core && npm i ytdl-core@npm:@distube/ytdl-core
> > ```
> 
> i get this error: `MinigetError: Status code: 403`
> what can i do  now???

Same question here

**Comment by hidemydreams** [comment]
> [@planet-bluto](https://github.com/planet-bluto)'s solution works, but only on Windows, on Debian I'm getting this error then:
> 
> ```
> webidl.is.File = webidl.util.MakeTypeAssertion(File)
>                                                ^
> 
> ReferenceError: File is not defined
>     at Object.<anonymous> (.../node_modules/undici/lib/web/webidl/index.js:531:48)
>     at Module._compile (node:internal/modules/cjs/loader:1364:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
>     at Module.load (node:internal/modules/cjs/loader:1203:32)
>     at Module._load (node:internal/modules/cjs/loader:1019:12)
>     at Module.require (node:internal/modules/cjs/loader:1231:19)
>     at require (node:internal/modules/helpers:177:18)
>     at Object.<anonymous> (.../test/node_modules/undici/lib/web/fetch/util.js:12:20)
>     at Module._compile (node:internal/modules/cjs/loader:1364:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> 
> Node.js v18.20.4
> ```

same
