### ISSUE TITLE
Getting 'This video is not available' with everything

### ISSUE THREAD

**Issue by Heroj04** [fent/node-ytdl-core#154]
I seem to be getting this error message regardless of the video link i use.

This is with ytdl.getinfo()

Error: This video is unavailable.
    at D:\Documents\My Servers\Radiobot\node_modules\ytdl-core\lib\info.js:61:25
    at IncomingMessage.<anonymous> (D:\Documents\My Servers\Radiobot\node_modules\miniget\lib\index.js:75:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by fent** [comment]
I can't reproduce this myself...

Can I see an example of how you're using it? The version you're using?

**Comment by FireController1847** [comment]
Same here. Have yet to be able to reproduce this bug.

**Comment by maxijonson** [comment]
Having this same error with every video too:

https://youtu.be/7nEmRJTbQhs
Error: This video is unavailable
    at /home/maxijonson/node_modules/ytdl-core/lib/info.js:208:16
    at IncomingMessage.res.on (/home/maxijonson/node_modules/miniget/lib/index.js:75:11)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by FireController1847** [comment]
Are you updated to the latest version @maxijonson ?

**Comment by maxijonson** [comment]
Oops I am sorry, updated the package to the latest version (instead of wanted version) and it is now working!

**Comment by FireController1847** [comment]
👍
