### ISSUE TITLE
how do i just download the audio of a video

### ISSUE THREAD

**Issue by w3bb01** [fent/node-ytdl-core#220]
how do i just download the audio of a video?

**Comment by TimeForANinja** [comment]
`ytdl('myvideoid', {filter: 'audioonly'})`

**Comment by w3bb01** [comment]
Thanks

**Comment by w3bb01** [comment]
if (!args || args.indexOf('-f') < 0 && args.indexOf('--format') < 0 &&
                    ^

TypeError: args.indexOf is not a function
    at Function.getInfo (C:\Users\JoshuaW\node_modules\youtube-dl\lib\youtube-dl.js:266:21)
    at module.exports (C:\Users\JoshuaW\node_modules\youtube-dl\lib\youtube-dl.js:105:8)
    at downloadSong (C:\Users\JoshuaW\Desktop\youtube-master\utube.js:14:15)
    at Object.<anonymous> (C:\Users\JoshuaW\Desktop\youtube-master\utube.js:21:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by w3bb01** [comment]
i got that error any ideas

**Comment by FireController1847** [comment]
Can you show us the code that's causing the error? Seems to have to do with yt.getInfi

**Comment by TimeForANinja** [comment]
`C:\Users\JoshuaW\node_modules\youtube-dl\lib\youtube-dl.js:266:21`
this is ytdl-core not youtube-dl

**Comment by FireController1847** [comment]
Oh, I didn't even see that. Yeah, he's right, this is ytdl-core not youtube-dl

**Comment by w3bb01** [comment]
ok thanks all

**Comment by w3bb01** [comment]
ill close this now
