### ISSUE TITLE
Error: This video is unavailable

### ISSUE THREAD

**Issue by HcgRandon** [fent/node-ytdl-core#258]
YTDL.getInfo requests failing with the follow error:
```
    at request ([omitted]/node_modules/ytdl-core/lib/info.js:220:16)
    at IncomingMessage.res.on ([omitted]/node_modules/miniget/lib/index.js:75:11)
    at emitNone (events.js:120:20)
    at IncomingMessage.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)```

**Comment by HcgRandon** [comment]
This issue can be fixed by remove `fromEmbed ? {} : { el: 'info' }` from https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L135 Looks like Google has removed this parameter as I get the follow error:
```
{ reason: 'Invalid parameters.',
  errorcode: '2',
  status: 'fail',
}
```

**Comment by HcgRandon** [comment]
see #260 for a quick hacky fix that you can use to get stuff working. It isn't good enough to be merged but it will hopefully get @fent on the right track.

**Comment by troffaholic** [comment]
Hey,

is this issue fixed? I am still getting this error.
Thanks.

**Comment by fent** [comment]
This was fixed, but the same error message could show up again for a new but similar issue. Feel free to open up a new issue with your stack trace and a youtube link where it happens.

**Comment by SwapnilSoni1999** [comment]
still getting error
