### ISSUE TITLE
Error: This video is unavailable

### ISSUE THREAD

**Issue by psq-cin** [fent/node-ytdl-core#262]
This error is happening with any video, using the README example with or without pipe.

    Error: This video is unavailable
        at request (C:\Users\usr\Documents\prog\node_modules\ytdl-core\lib\info.js:220:16)
        at IncomingMessage.res.on (C:\Users\usr\Documents\prog\node_modules\miniget\lib\index.js:75:11)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1055:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by psq-cin** [comment]
just saw issue #258 my bad :|
