### ISSUE TITLE
higestaudio quality options is not valid

### ISSUE THREAD

**Issue by oinkbark** [fent/node-ytdl-core#273]
Used with: ytdl(songPath,  {highWaterMark: Math.floor(64 * 1000), quality: 'highestaudio' })

```
Error: No such format found: highestaudio
at Object.exports.chooseFormat (node_modules/ytdl-core/lib/util.js:145:12)
at downloadFromInfoCallback (node_modules/ytdl-core/lib/index.js:62:21)
at getInfo (node_modules/ytdl-core/lib/index.js:25:5)
at util.parallel (node_modules/ytdl-core/lib/info.js:222:11)
at Object.exports.parallel (node_modules/ytdl-core/lib/util.js:436:5)
at sig.getTokens (node_modules/ytdl-core/lib/info.js:201:14)
at request (node_modules/ytdl-core/lib/sig.js:41:7)
at IncomingMessage.res.on (node_modules/miniget/lib/index.js:75:11)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
```

**Comment by fent** [comment]
Are you using ytdl-core version 0.19.0, where this feature was introduced?

**Comment by oinkbark** [comment]
I just installed a new version but I guess I did not double check the version that was installed. Sorry about that.
