### ISSUE TITLE
Error: This video is unavailable

### ISSUE THREAD

**Issue by chatn0ir07** [fent/node-ytdl-core#274]
Hello, coming straight to the point everytime i try to do 
`ytdl(LINK, { filter: (format) => format.container === 'flv'}).pipe(fs.createWriteStream("test.flv"));`, it returns
`Error: This video is unavailable.
    at request (c:\Users\lacoj\node_modules\ytdl-core\lib\info.js:64:25)
    at IncomingMessage.res.on (c:\Users\lacoj\node_modules\miniget\lib\index.js:75:11)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)`
can you help me?

**Comment by ajgeiss0702** [comment]
Did you find a solution to fix this? I am having the same problem
