### ISSUE TITLE
Error: This video is unavailable on any video

### ISSUE THREAD

**Issue by ajgeiss0702** [fent/node-ytdl-core#295]
Any video I try to download, I get this error:
```
Error: This video is unavailable.
    at request (/home/ubuntu/music/node_modules/ytdl-core/lib/info.js:64:25)
    at IncomingMessage.res.on (/home/ubuntu/music/node_modules/miniget/lib/index.js:75:11)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```
Any way i can fix this?

**Comment by nitaybz** [comment]
same issue here

**Comment by phablulo** [comment]
same here

**Comment by Devoxin** [comment]
Try ytdl-core 0.20.2, YouTube pushed a cipher change which broke older versions.

**Comment by phablulo** [comment]
Thanks, @Devoxin. I's working (:

**Comment by ajgeiss0702** [comment]
Thanks!
