### ISSUE TITLE
Error when attempting to run ffmpeg.js example code

### ISSUE THREAD

**Issue by wacharlb** [fent/node-ytdl-core#302]
When attempting to run the example script ffmpeg.js I get the following error (see below). The only modification I made to the code was to replace: 

const ytdl   = require('..');   which cause an error with,
const ytdl   = require('ytdl-core');

events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: No formats found with custom filter
    at Object.exports.chooseFormat (C:\Users\wacha\workspace\node_modules\ytdl-core\lib\util.js:116:14)
    at downloadFromInfoCallback (C:\Users\wacha\workspace\node_modules\ytdl-core\lib\index.js:62:21)
    at getInfo (C:\Users\wacha\workspace\node_modules\ytdl-core\lib\index.js:25:5)
    at util.parallel (C:\Users\wacha\workspace\node_modules\ytdl-core\lib\info.js:222:11)
    at Object.exports.parallel (C:\Users\wacha\workspace\node_modules\ytdl-core\lib\util.js:462:5)
    at sig.getTokens (C:\Users\wacha\workspace\node_modules\ytdl-core\lib\info.js:201:14)
    at request (C:\Users\wacha\workspace\node_modules\ytdl-core\lib\sig.js:41:7)
    at IncomingMessage.res.on (C:\Users\wacha\workspace\node_modules\miniget\lib\index.js:75:11)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)

**Comment by TimeForANinja** [comment]
guess your using sth like `videoonly` or `audioonly`
youtube doesn't provide `videoonly` and `audioonly` for all videos
(thats part of why highestaudio and highestvideo exist)
guess you found a rare occursion where only video+audio are provided
