### ISSUE TITLE
Error: The YouTube API key you provided was not a string.

### ISSUE THREAD

**Issue by mu3106** [fent/node-ytdl-core#304]
IS my API key wrong? I get this error: Error: The YouTube API key you provided was not a string.

**Comment by fent** [comment]
Could you post the stack trace, and what video did this happen in?

**Comment by faultyx** [comment]
Same, I get this error:
C:\Users\HPC\Desktop\EliteBot\node_modules\simple-youtube-api\src\index.js:26
        if (typeof key !== 'string') throw new Error('The YouTube API key you provided was not a string.');
                                     ^

Error: The YouTube API key you provided was not a string.
    at new YouTube (C:\Users\HPC\Desktop\EliteBot\node_modules\simple-youtube-api\src\index.js:26:44)
    at Object.<anonymous> (C:\Users\HPC\Desktop\EliteBot\centre.js:34:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by faultyx** [comment]
Never mind, fixed it

**Comment by StudNastty** [comment]
i have this issue also but yet my youtube key is correct

**Comment by fent** [comment]
this isn't related to ytdl since it does not use the youtube api

**Comment by ArKarDEV** [comment]
> Never mind, fixed it

how did you fixed it?

**Comment by ChopChoP534** [comment]
> Never mind, fixed it

howww

**Comment by Dudubbi** [comment]
> Non importa, aggiustalo

How bro, pls...

**Comment by LynxzA** [comment]
> Never mind, fixed it

can you tell me how you fixed it?

**Comment by Captaindeve** [comment]
how u fixed this bug
