### ISSUE TITLE
Video does not seem to load

### ISSUE THREAD

**Issue by SmileFX** [fent/node-ytdl-core#307]
Hey there!

I got an issue regarding the download of a video! I started programming a Discord Bot using this module back in January to play music. Everything worked fine until the day when the bot would just join the channel and leave again. His problem seems to be that the video could not be downloaded, logging that the video already ended. 

So I tried doing multiple thing but even the official discord.js dosumentation where a code example is located wouldnt help:
https://discord.js.org/#/docs/main/stable/class/VoiceConnection?scrollTo=playStream

I also tried just to get the Info about a video but still got an error. Here the error:

> UnhandledPromiseRejectionWarning: Error: Could not extract signature deciphering actions (\ytdl-core\lib\sig.js:36:18)

> Error: Could not extract signature deciphering actions
    at request (Bot\node_modules\ytdl-core\lib\sig.js:36:18)
    at IncomingMessage.res.on (Bot\node_modules\miniget\lib\index.js:75:11)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

I hope you can help or atleast tell me what I am doing wrong (The code example is very short, I can just be missing background stuff like an API key if this is needed).

**Comment by SmileFX** [comment]
Thanks for the help! I tried updating with npm update ytdl-core and it happened nothing, this worked!
