### ISSUE TITLE
Openload videos don't work

### ISSUE THREAD

**Issue by DaniPani** [fent/node-ytdl-core#311]
This is my code
```javascript
const loader = require('ytdl-core')
const fs = require('fs')

const video = loader('https://openload.co/f/Y4vQFIfNYdE/Mr.Robot.S01E01.Ciao.amico.1080p.mp4')

video.pipe(fs.createWriteStream('./files/video.mp4'))
```

But when I run it I got this error:
```javascript
Error: No video id found: https://openload.co/f/Y4vQFIfNYdE/Mr.Robot.S01E01.Ciao.amico.1080p.mp4
    at Object.exports.getURLVideoID (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\ytdl-core\lib\util.js:259:12)
    at Object.exports.getVideoID (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\ytdl-core\lib\util.js:281:20)
    at getInfo (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\ytdl-core\lib\info.js:48:17)
    at ytdl (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\ytdl-core\lib\index.js:19:3)
    at Object.<anonymous> (C:\Users\danie\Google Drive\Projects WebSites\downloader\prove.js:4:15)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
Emitted 'error' event at:
    at getInfo (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\ytdl-core\lib\index.js:21:14)
    at getInfo (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\ytdl-core\lib\info.js:49:35)
    at ytdl (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\ytdl-core\lib\index.js:19:3)
    [... lines matching original stack trace ...]
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
```
Node v9.90

**Comment by DaniPani** [comment]
Oh sorry I mixed it up with this: https://www.npmjs.com/package/youtube-dl
