### ISSUE TITLE
Error: could not extract signature deciphering actions

### ISSUE THREAD

**Issue by helloworld** [fent/node-ytdl-core#32]
I'm getting this error:

	 [Error: could not extract signature deciphering actions,
	     at /root/Spotify-to-MP3/node_modules/youtube-mp3-downloader/node_modules/ytdl-core/lib/sig.js:39:11,
	     at Request._callback (/root/Spotify-to-MP3/node_modules/youtube-mp3-downloader/node_modules/ytdl-core/lib/crequest.js:9:5),
	     at Request.self.callback (/root/Spotify-to-MP3/node_modules/youtube-mp3-downloader/node_modules/ytdl-core/node_modules/request/request.js:197:22),
	     at Request.EventEmitter.emit (events.js:98:17),
	     at Request.<anonymous> (/root/Spotify-to-MP3/node_modules/youtube-mp3-downloader/node_modules/ytdl-core/node_modules/request/request.js:1050:14),
	     at Request.EventEmitter.emit (events.js:117:20),
	     at IncomingMessage.<anonymous> (/root/Spotify-to-MP3/node_modules/youtube-mp3-downloader/node_modules/ytdl-core/node_modules/request/request.js:996:12),
	     at IncomingMessage.EventEmitter.emit (events.js:117:20),
	     at _stream_readable.js:920:16,
	     at process._tickCallback (node.js:415:13)]

How do I fix this?

**Comment by fent** [comment]
Just ran the tests, everything's good. What video does this happen in?
