### ISSUE TITLE
Cannot read property 'formats' of undefined when I try to downloadFromInfo()

### ISSUE THREAD

**Issue by johnRivs** [fent/node-ytdl-core#33]
I'm using Express. Everything works fine when using `ytdl(url, options)`, however
```js
var songInfo = ytdl.getInfo('https://www.youtube.com/watch?v=rHLbd3nvu88', { downloadURL: true });

ytdl.downloadFromInfo(songInfo, { filter: 'audioonly' }).pipe(res);
```
returns this error:
```
TypeError: Cannot read property 'formats' of undefined
    at downloadFromInfoCallback (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/index.js:44:38)
    at Function.downloadFromInfo (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/index.js:82:3)
    at /home/vagrant/www/lorem/index.js:17:10
    at Layer.handle [as handle_request] (/home/vagrant/www/lorem/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vagrant/www/lorem/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/vagrant/www/lorem/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/vagrant/www/lorem/node_modules/express/lib/router/layer.js:95:5)
    at /home/vagrant/www/lorem/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/vagrant/www/lorem/node_modules/express/lib/router/index.js:330:12)
    at next (/home/vagrant/www/lorem/node_modules/express/lib/router/index.js:271:10)
/home/vagrant/www/lorem/node_modules/ytdl-core/lib/sig.js:56
    callback(null, info);
    ^
TypeError: undefined is not a function
    at Object.exports.get (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/sig.js:56:5)
    at gotConfig (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:160:9)
    at /home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:55:9
    at null.<anonymous> (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:107:5)
    at emit (events.js:107:17)
    at readableAddChunk (/home/vagrant/www/lorem/node_modules/ytdl-core/node_modules/jstream/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at Readable.push (/home/vagrant/www/lorem/node_modules/ytdl-core/node_modules/jstream/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Transform.push (/home/vagrant/www/lorem/node_modules/ytdl-core/node_modules/jstream/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at CStream.onobjectavailable (/home/vagrant/www/lorem/node_modules/ytdl-core/node_modules/jstream/lib/index.js:126:14)
    at CStream.emit (events.js:129:20)
```
In fact, when I have this alone
```js
var songInfo = ytdl.getInfo('https://www.youtube.com/watch?v=rHLbd3nvu88', { downloadURL: true });
```
it throws:
```
/home/vagrant/www/lorem/node_modules/ytdl-core/lib/sig.js:56
    callback(null, info);
    ^
TypeError: undefined is not a function
    at Object.exports.get (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/sig.js:56:5)
    at gotConfig (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:160:9)
    at /home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:55:9
    at null.<anonymous> (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:107:5)
    at emit (events.js:107:17)
    at readableAddChunk (/home/vagrant/www/lorem/node_modules/ytdl-core/node_modules/jstream/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at Readable.push (/home/vagrant/www/lorem/node_modules/ytdl-core/node_modules/jstream/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Transform.push (/home/vagrant/www/lorem/node_modules/ytdl-core/node_modules/jstream/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at CStream.onobjectavailable (/home/vagrant/www/lorem/node_modules/ytdl-core/node_modules/jstream/lib/index.js:126:14)
    at CStream.emit (events.js:129:20)
```

**Comment by fent** [comment]
`ytld.getInfo()` is NOT synchronous, it needs to travel to youtube servers to get video info.

```js
ytdl.getInfo('https://www.youtube.com/watch?v=rHLbd3nvu88', { downloadURL: true }, function(err, songInfo) {
  if (err) throw err;
  ytdl.downloadFromInfo(songInfo, { filter: 'audioonly' }).pipe(res);
});
```

`ytdl()` is synchronous because it returns a readable stream, but its data isn't immediately available.

**Comment by johnRivs** [comment]
I see.. My knowledge on node is crippling me at the moment. This is what I'm ultimately trying:
```js
var app      = require('express')(),
    ytdl     = require('ytdl-core'),
    ffmpeg   = require('fluent-ffmpeg'),
    archiver = require('archiver'),
    async    = require('async');

app.get('/', function(req, res) {
    var archive = archiver.create('zip', {});

    ytdl.getInfo('https://www.youtube.com/watch?v=rHLbd3nvu88', { downloadURL: true }, function(err, songInfo) {
        archive.append(
            ffmpeg(
                ytdl('https://www.youtube.com/watch?v=rHLbd3nvu88', { filter: 'audioonly' })
            ).format('mp3').pipe(), {
                name: Date.now() + '.mp3'
            }
        );
    });
    
    res.setHeader('Content-disposition', 'attachment; filename=u2fy_' + Date.now() + '.zip');
    res.setHeader('Content-type', 'application/zip');

    archive.finalize().pipe(res);
});
```
When I do this without `getInfo()`, it works perfectly; the user recieves a zip file with the audio without it being created on the server. However, when I perform the same thing inside the callback function, I get an error by `archiver`: append: queue closed;

Any hint?

**Comment by fent** [comment]
That sounds like it might be an error with ytdl, but why do you need to call `ytdl.getInfo()` if you're not using `songInfo`?

You could also listen for the `info` event on the stream it returns.

```js
var video = ytdl('https://www.youtube.com/watch?v=rHLbd3nvu88', { filter: 'audioonly' });
video.on('info', function() {
});
```

**Comment by johnRivs** [comment]
Because I always get:
```js
url.js:110
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not object
    at Url.parse (url.js:110:11)
    at Object.urlParse [as parse] (url.js:104:5)
    at Object.exports.getVideoID (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/util.js:178:24)
    at getInfo (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:42:17)
    at ytdl (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/index.js:22:3)
    at /home/vagrant/www/lorem/index.js:27:25
    at Object.exports.get (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/sig.js:56:5)
    at gotConfig (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:160:9)
    at /home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:55:9
    at null.<anonymous> (/home/vagrant/www/lorem/node_modules/ytdl-core/lib/info.js:107:5)
```

About the info event, would it work in my case? I need to pass the stream to `ffmpeg()`.

**Comment by johnRivs** [comment]
I couldn't get that work, because of said `[Error: append: queue closed]` from `archiver`. Switched to:
```js
ffmpeg(
    ytdl.downloadFromInfo(songInfo, { filter: 'audioonly' })
)
```
Same thing though.

About the `info` event, would that work in my case? Because I need to pass a stream to `ffmpeg()`. How would that look like if I was to use the `info` event callback?

**Comment by fent** [comment]
do you need the `info`?

**Comment by johnRivs** [comment]
Oh I forgot, I used `Date.now()` instead of the actual thing I'm supposed to use, which is the name of the song. Sorry :P

**Comment by fent** [comment]
Oh, then something like

```js
var video = ytdl('https://www.youtube.com/watch?v=rHLbd3nvu88', { filter: 'audioonly' });
video.on('info', function(info) {
  archive.append(ffmpeg(video).format('mp3').pipe(), { name: info.title});
});
```

**Comment by johnRivs** [comment]
No luck :(

**Comment by johnRivs** [comment]
Ok, I've gone a different direction. My guess is, `archive.finalize()` gets piped to the response way to early, the queue closes and no more appends can happen.

So now I'm returning the archive but only finalizing it when everything is in:
```js
var archive = archiver.create('zip', {}),
    songs   = [
        'https://www.youtube.com/watch?v=vK_3AS2gavY'
    ],
    entries = 0;

var video = ytdl(songs[0], { filter: 'audioonly' });

video.on('info', function(info) {
    archive.append(ffmpeg(video).format('mp3').pipe(), { name: info.title + '.mp3'});
});

archive.on('entry', function(data) {
    entries++;

    if (songs.length === entries) {
        archive.finalize();
    }
});

res.setHeader('Content-disposition', 'attachment; filename=u2fy_' + Date.now() + '.zip');
res.setHeader('Content-type', 'application/zip');

archive.pipe(res);
```
It works, however, I can't figure out a way to make a loop in order to download more than 1 video.

**Comment by fent** [comment]
I don't understand why this wouldn't work for more than 1 video.

wouldn't you just loop for the list of video urls and append for each?
