### ISSUE TITLE
Problem with ytdl-core

### ISSUE THREAD

**Issue by STR4Z** [fent/node-ytdl-core#359]
Hello ! i wanted to make a bot and i got this error when i did !play "link"

(node:13724) UnhandledPromiseRejectionWarning: Error: No video id found: 
warning.js:18
    at Object.exports.getVideoID (c:\Users\Sanatra\Desktop\BD\node_modules\ytdl-core\lib\util.js:237:11)
    at getInfo (c:\Users\Sanatra\Desktop\BD\node_modules\ytdl-core\lib\info.js:47:17)
    at ytdl (c:\Users\Sanatra\Desktop\BD\node_modules\ytdl-core\lib\index.js:15:3)
    at Client.client.on (c:\Users\Sanatra\Desktop\BD\main.js:33:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

**Comment by DUFC-Liam** [comment]
Please send your code.

**Comment by STR4Z** [comment]
https://hasteb.in/avifixul.js

**Comment by DUFC-Liam** [comment]
On line 33 try
```js
const dispatcher = ytdl(args[0], { filter: 'audioonly' });
```

**Comment by STR4Z** [comment]
dispatcher has been already declared

**Comment by DUFC-Liam** [comment]
Actually, try
`<prefix>play https://www.youtube.com/watch?v=pgN-vvVVxMA`
[sample video]

The `"` in the command may be throwing `ytdl(args[0])` off as its looking for `"https://www.youtube.com/watch?v=pgN-vvVVxMA"` as the URL

**Comment by STR4Z** [comment]
okey

**Comment by TimeForANinja** [comment]
If u log args you should see args[0] being an empty string and args[1] being "play https://youtu.be/xxxxxxxxxxx"

**Comment by STR4Z** [comment]
now : The "file" argument must be of type string. Received type object

**Comment by DUFC-Liam** [comment]
In your code on line 33 put
```js
const stream = ytdl(args[1], { filter: 'audioonly' });
const dispatcher = connection.playStream(stream);
```

**Comment by STR4Z** [comment]
already did but now i got the error the "file" argument must be of type string

**Comment by STR4Z** [comment]
console.log(args[1])     
        const stream = ytdl(args[1], { filter: 'audioonly' });
        const dispatcher = connection.playStream(stream) now

**Comment by TimeForANinja** [comment]
Any stack with that error?

**Comment by STR4Z** [comment]
idk

**Comment by STR4Z** [comment]
(node:10692) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
warning.js:18
    at normalizeSpawnArguments (child_process.js:397:11)
    at Object.spawn (child_process.js:522:38)
    at new FfmpegProcess (c:\Users\Sanatra\Desktop\BD\node_modules\discord.js\node_modules\prism-media\src\transcoders\ffmpeg\FfmpegProcess.js:14:33)
    at FfmpegTranscoder.transcode (c:\Users\Sanatra\Desktop\BD\node_modules\discord.js\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:34:18)
    at MediaTranscoder.transcode (c:\Users\Sanatra\Desktop\BD\node_modules\discord.js\node_modules\prism-media\src\transcoders\MediaTranscoder.js:27:31)
    at Prism.transcode (c:\Users\Sanatra\Desktop\BD\node_modules\discord.js\node_modules\prism-media\src\Prism.js:13:28)
    at AudioPlayer.playUnknownStream (c:\Users\Sanatra\Desktop\BD\node_modules\discord.js\src\client\voice\player\AudioPlayer.js:97:35)
    at VoiceConnection.playStream (c:\Users\Sanatra\Desktop\BD\node_modules\discord.js\src\client\voice\VoiceConnection.js:478:24)
    at Client.client.on (c:\Users\Sanatra\Desktop\BD\main.js:34:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:10692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
