### ISSUE TITLE
Laggy audio on a discordjs bot

### ISSUE THREAD

**Issue by AnatoleLucet** [fent/node-ytdl-core#415]
So here's my code, i've tried it on my vps and my local unix but the probleme is always here. I've also tried some other issues fixs like removing the audioonly filter, differents hightWaterMark setup but it dosen't help.
It's not a probleme with my vps or my personnal connection.
When i said the audio is laggy that mean it's making some (for ex) 50ms cut on the audio, it also slow down and then speed up...

```Javascript
const ytdl = require('ytdl-core');

const Discord = require('discord.js');
const client = new Discord.Client();

const ytdlOptions = {
  filter: 'audioonly',
  quality: 'highestaudio',
  format: 'mp3',
  hightWaterMark: 1<<25
};
const streamOptions = {
  seek: 0,
  volume: 0.5,
  highWaterMark: 1
};


client.on('message', async (message) => {

  const args = message.content.slice('!').trim().split(/ +/g);
  const command = args.shift().toLowerCase();

  if (command === '!p') {
    const voiceConnection = await message.member.voiceChannel;

    voiceConnection.join().then(async connection => {
      const stream = ytdl(args.toString(), ytdlOptions);

      const dispatcher = connection.playStream(ytdl(args.toString(), ytdlOptions), streamOptions)
      .on('end', () => {
        dispatcher.end();
        console.log('ended');
        message.channel.send('ended');
      });

      await message.channel.send(`Now playing ${args}`);
    }).catch(err => console.error(err));
  }
});
```

Thanks for helping me, and sorry for my bad english.

**Comment by FireController1847** [comment]
About two hours ago Discord.js released something called "ytdl-core-discord." Would you mind trying that out and reporting back to us to see how it works?

https://www.npmjs.com/package/ytdl-core-discord

**Comment by amishshah** [comment]
Could you try removing the highWaterMark filter entirely? With the value you have set (32MB which is incredibly high) I couldn't get anything to play at all.

**Comment by AnatoleLucet** [comment]
@FireController1847 
It seems like ytdl-core-discord has a error :
```
TypeError: Prism is not a constructor
at new VoiceConnection (/app/node_modules/discord.js/src/client/voice/VoiceConnection.js:46:18)
at Promise (/app/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:63:22)
at new Promise (<anonymous>)
at ClientVoiceManager.joinChannel (/app/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:45:12)
at VoiceChannel.join (/app/node_modules/discord.js/src/structures/VoiceChannel.js:130:30)
at Object.exports.run (/app/commands/play.js:24:19)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
```


My code :

```Javascript
const ytdl = require('ytdl-core-discord');

const Discord = require('discord.js');
const client = new Discord.Client();

const ytdlOptions = {
  filter: 'audioonly',
  quality: 'highestaudio',
  format: 'mp3'
};
const streamOptions = {
  seek: 0,
  volume: 0.5
};

const play = async (connection, url) => {
  connection.playOpusStream(await ytdl(url));
};

client.on('message', async (message) => {

  const args = message.content.slice('!').trim().split(/ +/g);
  const command = args.shift().toLowerCase();

  if (command === '!p') {
    const voiceConnection = await message.member.voiceChannel;

    voiceConnection.join().then(async connection => {

      play(connection, args.toString());

      await message.channel.send(`Now playing ${args}`);
    }).catch(err => console.error(err));
  }
});
```

Am i doing something wrong ?

**Comment by amishshah** [comment]
Not sure what's happened, Discord.js 11.x uses an older version of prism whereas Discord.js 12 (master branch) and `ytdl-core-discord` use a newer version -- I assumed that npm would have installed both versions.

Could you try reinstalling discord.js and ytdl-core-discord to see if that fixes the issue?

If that doesn't work, could you try updating to master of discord.js (`npm i discordjs/discord.js`, you'll need git installed) and see if that fixes your issue?

Your code would then become:

```js
const ytdl = require('ytdl-core-discord');

const Discord = require('discord.js');
const client = new Discord.Client();

const play = async (connection, url) => {
  connection.play(await ytdl(url), { type: 'opus' });
};

client.on('message', async (message) => {

  const args = message.content.slice('!').trim().split(/ +/g);
  const command = args.shift().toLowerCase();

  if (command === '!p') {
    const voiceConnection = await message.member.voice.channel;

    voiceConnection.join().then(async connection => {

      play(connection, args.toString());

      await message.channel.send(`Now playing ${args}`);
    }).catch(err => console.error(err));
  }
});
```

**Comment by AnatoleLucet** [comment]
@amishshah As you thought docker (because i use docker) installed me two version of discord js in my modules, because i've forgot to dockerignore my node_module (stupid me).

So it seems to work really fine with ytdl-core-discord on my local computer and on my vps.
Thanks for your help. 😃
