### ISSUE TITLE
Video not available only on Firebase Function

### ISSUE THREAD

**Issue by loafofpiecrust** [fent/node-ytdl-core#426]
Hello, I'm writing a Firebase cloud function that uses `ytdl-core` to grab video format information.
```js
const info = await ytdl.getInfo(videoId)
```
It works fine running on my local machine, but once deployed to a google server, I get this error on some videos:
```
Error: This video is not available.
    at request (/srv/functions/node_modules/ytdl-core/lib/info.js:52:25)
    at PassThrough.stream.on (/srv/functions/node_modules/miniget/lib/index.js:176:30)
    at PassThrough.emit (events.js:189:13)
    at PassThrough.EventEmitter.emit (domain.js:459:23)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19
```
Here are some of the video IDs it happens with: `EI-WSXUnJA0`, `K_sHDRnWuo0`, `ceaKr_nrDuI`. For other videos it works fine (i.e. `ugx9r_bgl2Y`, `tYnVaoHrPPg`), and I'm not sure what the pattern is.
Any idea what could be going on here?

**Comment by kartik1225** [comment]
Is this happening on all video ids or just on some ids?
Please note that if you are on the `spark` plan ( the free one ) then this plan does not have internet access from outside of `google cloud platform` network, therefore ytdl will not work.

**Comment by fent** [comment]
please check that you are using the latest version of ytdl-core. and are you downloading certain formats?
