### ISSUE TITLE
TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#429]
Hello, i really often get the following error while using the **getInfo()** method and i can't catch it. The process exits directly.

```
_http_outgoing.js:359
throw new TypeError('The header content contains invalid characters');

TypeError: The header content contains invalid characters
at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:359:11)
at model.info (/modules/downloader/router.js:39:13)
at ytdl.getInfo (/modules/downloader/model.js:18:11)
at fn (/node_modules/ytdl-core/lib/info.js:373:9)
at util.parallel (/node_modules/ytdl-core/lib/info.js:240:11)
at Object.exports.parallel (/node_modules/ytdl-core/lib/util.js:393:5)
at sig.getTokens (/node_modules/ytdl-core/lib/info.js:218:14)
at Object.exports.getTokens (/node_modules/ytdl-core/lib/sig.js:27:5)
at exports.getBasicInfo (/node_modules/ytdl-core/lib/info.js:196:11)
 at fn (/node_modules/ytdl-core/lib/info.js:373:9)
```

My Code: 
```
exports.info = (doc, cb) => {

  if(!_.isUndefined(doc._id)) {
    try {
      ytdl.getInfo(doc._id, (err, info) => {
        if(!err && info) {
          cb(info);
          return;
        } else if(err) {
          logger.log(err);
        }
        cb(null);
      });
    } catch(e) {
      console.log("[Error]: Error was catched and code can go on!");
      console.log(e);
      cb(null);
    }
    return;
  }
  cb(null);
};
```

Anybody have a fix or workaround for me?

**Comment by fent** [comment]
the error is coming from `modules/downloader/router.js`. maybe because `cb()` is being called multiple times
