### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by BRAVO68WEB** [fent/node-ytdl-core#447]
(node:960) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Url.parse (url.js:155:3)
    at Object.urlParse [as parse] (url.js:150:13)
    at Object.exports.getURLVideoID (c:\DiscordBot\musicbot\node_modules\ytdl-core\lib\util.js:273:22)
    at Object.exports.getVideoID (c:\DiscordBot\musicbot\node_modules\ytdl-core\lib\util.js:304:20)
    at Object.exports.<computed> [as getFullInfo] (c:\DiscordBot\musicbot\node_modules\ytdl-core\lib\info.js:355:21)
    at c:\DiscordBot\musicbot\node_modules\ytdl-core\lib\info.js:348:24
    at new Promise (<anonymous>)
    at Function.exports.<computed> [as getInfo] (c:\DiscordBot\musicbot\node_modules\ytdl-core\lib\info.js:347:14)
    at execute (c:\DiscordBot\musicbot\index.js:54:30)
(node:960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NightYoshi370** [comment]
Post the code

**Comment by TimeForANinja** [comment]
I mean your answer is in the Error - the first param you pass to ytdl-core is not of type string

**Comment by paul-hanneforth** [comment]
This happens to me as well, but the parameter I pass isn't null!

**Comment by paul-hanneforth** [comment]
I did a little debugging, the error come's from this line `const html5player = urllib.resolve(VIDEO_URL, info.html5player);`. It's located in the lib/info.js file in the exports.getInfo function. The issue come's from the html5player property sometimes seemingly randomly being undefined.
