### ISSUE TITLE
Could not extract html5player key

### ISSUE THREAD

**Issue by dimaslanjaka** [fent/node-ytdl-core#449]
> Could not extract html5player key: https://www.youtube.com/yts/jsbin/player_ias-vflK6rDhN/en_US/base.js
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: Input stream error: No such format found: highestaudio
    at PassThrough.<anonymous> (D:\l3n4r0x-ytdl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (events.js:198:13)
    at Immediate.<anonymous> (D:\l3n4r0x-ytdl\node_modules\ytdl-core\lib\index.js:57:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at emitEnd (D:\l3n4r0x-ytdl\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at PassThrough.<anonymous> (D:\l3n4r0x-ytdl\node_modules\fluent-ffmpeg\lib\processor.js:454:15)
    at PassThrough.emit (events.js:198:13)
    [... lines matching original stack trace ...]
    at processImmediate (timers.js:658:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-js-getting-started@0.2.6 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-js-getting-started@0.2.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\windows 10\AppData\Roaming\npm-cache\_logs\2019-07-15T17_39_08_618Z-debug.log

**package.json**
`{
  "name": "node-js-getting-started",
  "version": "0.2.6",
  "description": "A sample Node.js app using Express 4",
  "engines": {
    "node": "6.10.2"
  },
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "body-parser": "^1.19.0",
    "ejs": "2.5.6",
    "express": "^4.17.1",
    "fluent-ffmpeg": "^2.1.2",
    "ytdl-core": "^0.14.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/heroku/node-js-getting-started"
  },
  "keywords": [
    "node",
    "heroku",
    "express"
  ],
  "license": "MIT",
  "devDependencies": {
    "@types/express": "^4.0.35",
    "@types/node": "^7.0.29"
  }
}
`

**Comment by fent** [comment]
`package.json` is listing ytdl-core version at 0.14.2. please use the latest version, which is 0.29.3

**Comment by dimaslanjaka** [comment]
many thanks. fixed by 
`npm install ytdl-core@latest`
