### ISSUE TITLE
What does that means

### ISSUE THREAD

**Issue by cybermarkus1** [fent/node-ytdl-core#50]
Error: status code 302
    at ClientRequest.<anonymous> (/home/ymp3/node_modules/ytdl-core/lib/index.js:57:28)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24)

**Comment by thepieterdc** [comment]
Getting this error too; but only if I specify the filter: 'audioonly' format, so it's not with all video formats.

**Comment by cybermarkus1** [comment]
yeah for me too, maybe its a youtube restriction thing or is a plugin thing?

**Comment by thepieterdc** [comment]
I've pushed a fix

**Comment by cybermarkus1** [comment]
ah ok, thanks! but is that a PR right?

**Comment by thepieterdc** [comment]
@cybermarkus1 yes correct, @fent needs to merge it.

**Comment by cybermarkus1** [comment]
ok! thanks!
