### ISSUE TITLE
HTTP Error 501 when using a proxy

### ISSUE THREAD

**Issue by DELUUXE** [fent/node-ytdl-core#530]
When using a proxy, ytdl-core almost always returns an Http 501 error or a "Too many redirects" error.

I am using the following request options in the ytdl.getInfo function
```js
{
    requestOptions: {
        transform: (parsed) => {
            parsed.maxRedirects = 10
            parsed.protocol = 'http:'
            return {
                host: body.ip, //body.ip contains the ip adress of the proxy (which is random everytime)
                protocol: 'http:',
                port: body.port, //body.port contains the port of the proxy (which is random everytime, is matching for the proxy ip)
                path: parsed.href,
                maxRedirects: 10,
                headers: { Host: parsed.host },
            }
        },
    },
}
```
Or with the ones specified in the proxy example.

## snipped of test code

```js
ytdl.getInfo('https://www.youtube.com/watch?v=JMT5TiKZ_rk', {
    requestOptions: {
        transform: (parsed) => {
            return {
                host: proxy.ip,
                port: proxy.port,
                path: parsed.href,
                headers: {
                    Host: parsed.host
                },
                protocol: 'http:',
            }
        },
    },
}, function (err, info) {
    if (err) {
        console.error(err)
        return
    }
    console.log(info.title)
})
```

## stack straces
```
Error: Status code: 501
at ClientRequest.httpLib.get (.\node_modules\miniget\dist\index.js:128:27)
at Object.onceWrapper (events.js:277:13)
at ClientRequest.emit (events.js:189:13)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
at Socket.socketOnData (_http_client.js:449:20)
at Socket.emit (events.js:189:13)
at addChunk (_stream_readable.js:288:12)
at readableAddChunk (_stream_readable.js:269:11)
at Socket.Readable.push (_stream_readable.js:224:10)
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
```

```
Error: Too many redirects
at ClientRequest.httpLib.get (.\node_modules\miniget\dist\index.js:113:42)
at Object.onceWrapper (events.js:277:13)
at ClientRequest.emit (events.js:189:13)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
at Socket.socketOnData (_http_client.js:449:20)
at Socket.emit (events.js:189:13)
at addChunk (_stream_readable.js:288:12)
at readableAddChunk (_stream_readable.js:269:11)
at Socket.Readable.push (_stream_readable.js:224:10)
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
```

## versions

- node@v11.4.0
- ytdl-core@1.0.2

**Comment by RocoGreen** [comment]
I need more infos about your code
How do you get `body` ?

**Comment by DELUUXE** [comment]
> I need more infos about your code
> How do you get `body` ?

body contains details about a proxy server, requested from a rotating proxy api.

**Comment by DELUUXE** [comment]
I read something about using request instead of mini-get in this PR: https://github.com/fent/node-ytdl-core/pull/526#issuecomment-557935191

might that have something to do with this?

**Comment by RocoGreen** [comment]
I dunno, you code seems to be correct so I need to know how do you get this rotating proxy?

**Comment by DELUUXE** [comment]
> I dunno, you code seems to be correct so I need to know how do you get this rotating proxy?

i already provided the link to the website of my rotating proxy provider

> > I need more infos about your code
> > How do you get `body` ?
> 
> body contains details about a proxy server, requested from a rotating proxy api.
> To be specific from: [proxyorbit.com](https://proxyorbit.com)

they also provide 200 requests to their api for free if you need to test it.

**Comment by DELUUXE** [comment]
I guess that ill be trying to re-write this and use request instead of mini-get?

**Comment by DonikaV** [comment]
Error: reCAPTCHA form show here https://github.com/mh4ck/node-ytdl-core

**Comment by fent** [comment]
as commented on https://github.com/fent/node-ytdl-core/issues/524, try removing the `protocol` from the transform. and let's keep this discussion in one issue.
