### ISSUE TITLE
Cannot find module 'm3u8stream/lib/parse-time'

### ISSUE THREAD

**Issue by YuryRegis** [fent/node-ytdl-core#531]
After upgrade ytdl-core I got this error:
```js
(node:1) UnhandledPromiseRejectionWarning: Error: Cannot find module 'm3u8stream/lib/parse-time'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.\u003canonymous\u003e (/home/node/node_modules/ytdl-core/lib/info-extras.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) ``` 

Using ytdl-core version 0.29.7 its all good. How can I fix it?

**Comment by TimeForANinja** [comment]
update dependencies

**Comment by YuryRegis** [comment]
Here are my dependecies, is something missed or out-of-date?
```js
"dependencies": {
    "bufferutil": "^4.0.1",
    "discord.js": "^11.5.1",
    "ffmpeg": "",
    "jimp": "^0.6.8",
    "opusscript": "0.0.6",
    "parse-time": "",
    "html-entities": "^1.1.3",
    "m3u8stream": "^0.6.3",
    "miniget": "^1.6.0",
    "sax": "^1.1.3",
    "simple-youtube-api": "^5.2.1",
    "ytdl-core": "0.29.7"
  } ```

**Comment by fent** [comment]
update to latest ytdl-core

**Comment by DonikaV** [comment]
i updated and have same error...

**Comment by YangVincent** [comment]
I'm on the latest ytdl-core, but still getting this issue.
