### ISSUE TITLE
getInfo seems like not executed on the server but same code works locally

### ISSUE THREAD

**Issue by DonikaV** [fent/node-ytdl-core#532]
Hi there. 
```ts
getInfo(videoId)
          .then(info => {
              res.json(info).end();
              convertAndDownload(userBitrate, info, res, socket, fileName);
          })
          .then(err => res.status(500).json({error: errMsg}));
```

locally all works fine, however on server nothing happens. No erors, nothing. If i will put console.log() as a first line inside getInfo - nothing... just silence

**Comment by DonikaV** [comment]
I am trying with proxy. But i have 
```js
(node:11480) UnhandledPromiseRejectionWarning: Error: Status code: 400
    at ClientRequest.httpLib.get (...../node_modules/miniget/dist/index.js:128:27)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:11480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
My code is 
```

const requestOptions = {
    transform: (parsed) => {
        return {
            host: myHost,
            port: "myPort",
            path: parsed.href,
            headers: {
                Host: parsed.host
            },
            protocol: 'http:',
            login: "login",
            password: "pass"
        };
    }
};
getInfo(videoId, {requestOptions})
          .then(info => {
              res.json(info).end();
        
              convertAndDownload(userBitrate, info, res, socket, fileName);
          })
          .then(err => {
              console.log(err);
              res.status(500).json({error: errMsg})
          });
       
```

**Comment by fent** [comment]
> locally all works fine, however on server nothing happens. No erors, nothing. If i will put console.log() as a first line inside getInfo - nothing... just silence

if there is an error, the second `.then` isn't catching it. `.then` requires a 2nd function if you want to catch a promise error, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then


for proxy usage, look at the examples folder, or follow the discussion on https://github.com/fent/node-ytdl-core/issues/524

**Comment by DonikaV** [comment]
So it should be something like this? 
```js

return doSomething(foo).then(function(result) {
  // ...
}).then(function(result2) {
  // ...
}).then(function(result3) {
  // ...
}).catch(function(error) {
  // ...
}).finally(function() {
  // ...
});
```

**Comment by DonikaV** [comment]
Or this 
```js
getInfo(videoId).then(
              function(info) {
                  res.json(info).end();
                  convertAndDownload(userBitrate, info, res, socket, fileName);
            }, function(error) {
                  console.log(error);
                  res.status(500).json({error: errMsg});
            });
```

**Comment by DonikaV** [comment]
with https-proxy-agent 
{ Error: connect EINVAL 0.0.254.209:80 - Local (0.0.0.0:0)
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at internalConnect (net.js:977:16)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1119:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'connect',
  address: '0.0.254.209',
  port: 80 }

**Comment by DonikaV** [comment]
```js
try {
            await getInfo(videoId, { requestOptions: agent }, (err, info) => {
                if (err) {
                    console.log(err);
                    throw err;
                }
                if (info) {
                    res.json(info).end();
                    convertAndDownload(userBitrate, info, res, socket, fileName);
                }
            });
        } catch (error) {
            console.log("That did not go well.");
            console.error(error);
        }
```
Returns huge error 
```::1 - - [08/Dec/2019:10:05:15 +0000] "GET /favicon.ico HTTP/1.1" 200 14542 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
{"error":{},"level":"error","message":"uncaughtException: The \"msecs\" argument must be of type number. Received type object\nTypeError [ERR_INVALID_ARG_TYPE]: The \"msecs\" argument must be of type number. Received type object\n    at validateNumber (internal/validators.js:130:11)\n    at validateTimerDuration (internal/timers.js:146:3)\n    at TLSSocket.Socket.setTimeout (net.js:407:11)\n    at setRequestSocket (_http_agent.js:361:10)\n    at handleSocketCreation_Inner (_http_agent.js:349:7)\n    at oncreate (_http_agent.js:224:5)\n    at Agent.createSocket (_http_agent.js:229:5)\n    at Agent.addRequest (_http_agent.js:185:10)\n    at new ClientRequest (_http_client.js:249:16)\n    at Object.request (https.js:289:10)\n    at Object.request (/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js:25:22)\n    at Object.https.get (/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js:48:21)\n    at doDownload (/Users/donika/Sites/mp3-ytb/node_modules/miniget/dist/index.js:110:25)\n    at process._tickCallback (internal/process/next_tick.js:61:11)","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"msecs\" argument must be of type number. Received type object\n    at validateNumber (internal/validators.js:130:11)\n    at validateTimerDuration (internal/timers.js:146:3)\n    at TLSSocket.Socket.setTimeout (net.js:407:11)\n    at setRequestSocket (_http_agent.js:361:10)\n    at handleSocketCreation_Inner (_http_agent.js:349:7)\n    at oncreate (_http_agent.js:224:5)\n    at Agent.createSocket (_http_agent.js:229:5)\n    at Agent.addRequest (_http_agent.js:185:10)\n    at new ClientRequest (_http_client.js:249:16)\n    at Object.request (https.js:289:10)\n    at Object.request (/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js:25:22)\n    at Object.https.get (/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js:48:21)\n    at doDownload (/Users/donika/Sites/mp3-ytb/node_modules/miniget/dist/index.js:110:25)\n    at process._tickCallback (internal/process/next_tick.js:61:11)","exception":true,"date":"Sun Dec 08 2019 11:05:17 GMT+0100 (Central European Standard Time)","process":{"pid":26254,"uid":501,"gid":20,"cwd":"/Users/donika/Sites/mp3-ytb","execPath":"/usr/local/bin/node","version":"v10.16.0","argv":["/usr/local/bin/node","/Users/donika/Sites/mp3-ytb/bin/www"],"memoryUsage":{"rss":79147008,"heapTotal":64847872,"heapUsed":32123136,"external":20018544}},"os":{"loadavg":[4.08447265625,2.70068359375,2.23876953125],"uptime":309980},"trace":[{"column":11,"file":"internal/validators.js","function":"validateNumber","line":130,"method":null,"native":false},{"column":3,"file":"internal/timers.js","function":"validateTimerDuration","line":146,"method":null,"native":false},{"column":11,"file":"net.js","function":"TLSSocket.Socket.setTimeout","line":407,"method":"setTimeout","native":false},{"column":10,"file":"_http_agent.js","function":"setRequestSocket","line":361,"method":null,"native":false},{"column":7,"file":"_http_agent.js","function":"handleSocketCreation_Inner","line":349,"method":null,"native":false},{"column":5,"file":"_http_agent.js","function":"oncreate","line":224,"method":null,"native":false},{"column":5,"file":"_http_agent.js","function":"Agent.createSocket","line":229,"method":"createSocket","native":false},{"column":10,"file":"_http_agent.js","function":"Agent.addRequest","line":185,"method":"addRequest","native":false},{"column":16,"file":"_http_client.js","function":"new ClientRequest","line":249,"method":null,"native":false},{"column":10,"file":"https.js","function":"Object.request","line":289,"method":"request","native":false},{"column":22,"file":"/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js","function":"Object.request","line":25,"method":"request","native":false},{"column":21,"file":"/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js","function":"Object.https.get","line":48,"method":"get","native":false},{"column":25,"file":"/Users/donika/Sites/mp3-ytb/node_modules/miniget/dist/index.js","function":"doDownload","line":110,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":61,"method":"_tickCallback","native":false}]}```

**Comment by fent** [comment]
you're passing `agent` to `requestOptions`, you need to pass an object with `agent`

**Comment by DonikaV** [comment]
@fent yes, i changed this , i put code here https://github.com/fent/node-ytdl-core/issues/524
