### ISSUE TITLE
Error: This video is unavailable

### ISSUE THREAD

**Issue by felix-voicehub** [fent/node-ytdl-core#535]
Hi,

I'm on 1.0.3 and getting this error:

```
Error: This video is unavailable
    at /Users/me/Desktop/dev/youtube-dl-service/node_modules/ytdl-core/lib/info.js:255:16
    at /Users/me/Desktop/dev/youtube-dl-service/node_modules/ytdl-core/lib/info.js:367:30
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Emitted 'error' event on PassThrough instance at:
    at /Users/me/Desktop/dev/youtube-dl-service/node_modules/ytdl-core/lib/index.js:19:14
    at /Users/me/Desktop/dev/youtube-dl-service/node_modules/ytdl-core/lib/info.js:370:25
    at /Users/me/Desktop/dev/youtube-dl-service/node_modules/ytdl-core/lib/info.js:255:7
    at /Users/me/Desktop/dev/youtube-dl-service/node_modules/ytdl-core/lib/info.js:367:30
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

The video is this one:
`https://www.youtube.com/watch?v=AXpRNd6K2hY`

This only occurs for this very video. Code:

```
const stream = ytdl(youtube_url);
const task = new Ffmpeg(stream).audioBitrate(128);
// ... ffmpeg processing
```

Any ideas?

**Comment by felix-voicehub** [comment]
Extremely weird, just started working. No idea why, it failed on me like 50 times in the last couple of days.
