### ISSUE TITLE
No video id found

### ISSUE THREAD

**Issue by TimeCrafter1** [fent/node-ytdl-core#536]
I made a Discord bot with ytdl-core and it worked fine until today now every time i want to use it it says:
(node:7491) UnhandledPromiseRejectionWarning: Error: No video id found: play
    at Object.exports.getURLVideoID (/rbd/pnpm-volume/a610284f-456c-4912-92bf-5cb18d35ec00/node_modules/.registry.npmjs.org/ytdl-core/1.0.3/node_modules/ytdl-core/lib/util.js:271:12)
    at Object.exports.getVideoID (/rbd/pnpm-volume/a610284f-456c-4912-92bf-5cb18d35ec00/node_modules/.registry.npmjs.org/ytdl-core/1.0.3/node_modules/ytdl-core/lib/util.js:293:20)
    at Function.exports.(anonymous function) [as getInfo] (/rbd/pnpm-volume/a610284f-456c-4912-92bf-5cb18d35ec00/node_modules/.registry.npmjs.org/ytdl-core/1.0.3/node_modules/ytdl-core/lib/info.js:327:21)
    at ytdl (/rbd/pnpm-volume/a610284f-456c-4912-92bf-5cb18d35ec00/node_modules/.registry.npmjs.org/ytdl-core/1.0.3/node_modules/ytdl-core/lib/index.js:17:8)

**Comment by fent** [comment]
you passed the string "play" to ytdl-core

**Comment by TimeCrafter1** [comment]
OOf i am sry for the time I wasted for you.
I pushed the Play Argument to the Queue not the link.
I hope I don't wasted too much time of yours.
