### ISSUE TITLE
Tests fail on windows but pass on linux

### ISSUE THREAD

**Issue by Aasim-A** [fent/node-ytdl-core#577]
#### Using: Node v12.16.1 / NPM v6.13.7
Hi, I tried to download the repo and run the tests on windows but the tests fail, I tried to look into what's causing the problem but couldn't figure it out, the command ```npm run test:irl``` passes without a problem but ```npm test``` fails and it gives this output:
```
Download video
    √ Should be pipeable and data equal to stored file (70ms)
    √ Fails gracefully if error getting info
    destroy stream
      immediately
        √ Doesn't start the download
      right after request is made
        √ Doesn't start the download
      after download has started
        √ Download is incomplete
    stream disconnects before end
      √ Still downloads the whole video
      with range
        √ Downloads from the given `start` to `end`
    with start range
      √ Range added to download headers
    with end range
      √ Range added to download headers
    with begin
      √ Begin added to download URL
    with a bad filter
      √ Emits error
    that is broadcasted live
      √ Begins downloading video succesfully (333ms)
      end download early
        √ Stops downloading video (206ms)
      from a dash-mpd itag
        √ Begins downloading video succesfully

  extras.getVideoDescription()
    √ Retrieves formatted video description
    √ Fallbacks to empty description if element not found

  extras.getAuthor()
    √ Returns video author object
    watch page without author
      √ Returns empty object if author not found
    from a rental
      √ Returns video author object

  extras.getVideoMedia()
    √ Returns media object
    On a video with an older game
      √ Returns media object
    On a video with a game with an image
      √ Returns media object

  extras.getPublished()
    √ Retrieves formatted published date

  extras.getRelatedVideos()
    1) Returns related videos
    Without `rvs` params
      2) Unable to find some view counts
    With an unparseable video
      √ Cathes errors
    When error parsing
      √ Returns empty array

  extras.getLikes()
    √ Returnes like count
    With no likes
      √ Does not return likes

  extras.getDislikes()
    √ Returnes dislike count
    With no dislikes
      √ Does not return dislikes

  ytdl.getInfo()
    From a regular video
      √ Retrieves correct metainfo
      Use ytdl.getBasicInfo()
        √ Retrieves just enough metainfo
        Followed by ytdl.getInfo()
          √ Does not make extra requests
        Use `ytdl.downloadFromInfo()`
          √ Throw error
      Use `ytdl.downloadFromInfo()`
        √ Retrives video file
      Pass request options
        √ Request gets called with more headers
      Using the promise API
        √ Retrieves correct metainfo
        On a video that fails
          √ Error is caught
      Called twice
        √ Makes requests once
    From a non-existant video
      √ Should give an error
    From an age restricted video
      √ Returns correct video metainfo
      √ Fails gracefully when unable to find config
    From a video that was live streamed but not currently live
      √ Returns correct video metainfo
    From a video that is not embeddable outside of YouTube
      √ Returns correct video metainfo
    From a rental
      √ Returns an error about it
    With a bad video ID
      √ Returns an error
    When there is an error requesting one of the pages
      √ Fails gracefully when unable to get watch page
      √ Fails gracefully when unable to parse config
      √ Fails gracefully when unable to get embed page
      √ Fails gracefully when unable to get video info page
      √ Fails gracefully when get video info page errors
      √ Fails gracefully when unable to get html5player tokens
      √ Fails gracefully when unable to get m3u8 playlist
      √ Fails gracefully when no formats are found (102ms)
      √ Fails gracefully when unable to parse player_response

  Get tokens
    √ Returns a set of tokens
    Hit the same video twice
      √ Gets html5player tokens from cache
    Get a bad html5player file
      √ Gives an error
    Unable to find key in filename
      √ Warns the console, still attempts to get tokens
    Unable to find tokens
      √ Gives an error

  Signature decipher
    extract deciphering actions
      √ Returns the correct set of actions
    properly apply actions based on tokens
      √ reverses
      √ swaps head and position
      √ slices
      √ real set of tokens

  Set download URL
    √ Adds signature to download URL
    With a badly formatted URL
      √ Does not set URL
      With debug on
        √ Logs to console
    Without a URL
      √ Does not set URL
      With debug on
        √ Logs to console

  util.sortFormats()
    With `highest` given
      √ Sorts available formats from highest to lowest quality

  util.chooseFormat
    √ Is exposed in module
    with no options
      √ Chooses highest quality
    With lowest quality wanted
      √ Chooses lowest itag
    With highest audio quality wanted
      √ Chooses highest audio itag
    With lowest audio quality wanted
      √ Chooses lowest audio itag
    With highest video quality wanted
      √ Chooses highest video itag
    With lowest video quality wanted
      √ Chooses lowest video itag
    With itag given
      √ Chooses matching format
      that is not in the format list
        √ Returns an error
    With list of itags given
      √ Chooses matching format
    With format object given
      √ Chooses given format without searching
    With filter given
      that matches a format
        √ Chooses a format
      that does not match a format
        √ Returns an error

  util.filterFormats
    √ Tries to find formats that match
    √ Is exposed in module
    that doesn't match any format
      √ Returns an empty list
    With `video` given
      √ Returns only matching formats
    With `videoonly` given
      √ Returns only matching formats
    With `audio` given
      √ Returns only matching formats
    With `audioonly` given
      √ Returns only matching formats
    With `audioandvideo` given
      √ Returns only matching formats
    With unsupported filter given
      √ Returns only matching formats

  util.between()
    √ `left` positioned at the start
    √ somewhere in the middle
    √ not found
    √ `right` before `left`
    √ `right` not found

  util.getURLVideoID()
    √ Is exposed in module
    √ Retrives the video ID from the url

  util.getVideoID()
    √ Is exposed in module
    √ Retrives the video ID from the url

  util.validateID()
    √ Is exposed in module
    √ Retrieves whether a string includes a video ID

  util.validateURL()
    √ Is exposed in module
    √ Retrieves whether a string includes a parsable video ID

  util.addFormatMeta()
    √ Adds extra metadata to a format
    With an unknown itag
      √ Adds does not add extra metadata to a format


  107 passing (1s)
  2 failing

  1) extras.getRelatedVideos()
       Returns related videos:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_plus__WEBPACK_IMPORTED_MODULE_0__[k].apply(assert_plus__WEBPACK_IMPORTED_MODULE_0__[k], arguments)

      + expected - actual

      -false
      +true

      at Function.AssertDiff.<computed> [as ok] (node_modules\assert-diff\lib\index.js:123:49)
      at E:\Coding\Contributions\node-ytdl-core\test\info-extras-test.js:180:14
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

  2) extras.getRelatedVideos()
       Without `rvs` params
         Unable to find some view counts:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_plus__WEBPACK_IMPORTED_MODULE_0__[k].apply(assert_plus__WEBPACK_IMPORTED_MODULE_0__[k], arguments)

      + expected - actual

      -false
      +true

      at Function.AssertDiff.<computed> [as ok] (node_modules\assert-diff\lib\index.js:123:49)
      at E:\Coding\Contributions\node-ytdl-core\test\info-extras-test.js:198:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)




=============================== Coverage summary ===============================
Statements   : 97.01% ( 616/635 )
Branches     : 95.98% ( 310/323 )
Functions    : 97.75% ( 87/89 )
Lines        : 97.13% ( 576/593 )
================================================================================
```
After that I tried to run them on linux ```ubuntu 18.04``` and all of the tests passed.

**Comment by fent** [comment]
strange. at some point, I had windows and mac on the [list of os's](https://github.com/fent/node-ytdl-core/blob/ddd8600785b0ac9523ab565e143a008b18422fc2/.github/workflows/nodejs.yml#L12) to test, and [they all passed](https://github.com/fent/node-ytdl-core/actions/runs/9982571)

the lines the errors point to don't even look like they would work differently on windows, `getRelatedVideos` doesn't have platform specific code... I think

**Comment by Aasim-A** [comment]
yeah, it's pretty confusing, after some digging, it boiled down to ```utils.between()``` returning an empty string, for some reason when searching for ```',\n'``` it doesn't recognize that and returns an empty array of related videos
