### ISSUE TITLE
Could not extract html5player key

### ISSUE THREAD

**Issue by MidSpike** [fent/node-ytdl-core#591]
```
----------------------------------------------------------------------------------------------
https://www.youtube.com/watch?v=A1DfK081agE
Could not extract html5player key: https://www.youtube.com/s/player/5e4e8d5d/player_ias.vflset/en_US/base.js
----------------------------------------------------------------------------------------------
Trace: uncaughtException at: Error: Status code: 403
    at ClientRequest.<anonymous> (C:\Users\ME\Desktop\MYPROJECT\node_modules\ytdl-core\node_modules\miniget\dist\index.js:128:27)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
    at process.<anonymous> (C:\Users\ME\Desktop\MYPROJECT\script.js:2494:13)
    at process.emit (events.js:210:5)
    at process._fatalException (internal/process/execution.js:150:25)
----------------------------------------------------------------------------------------------
```

**Comment by Will3126** [comment]
I got an issue like that before.

**Comment by mh4ck** [comment]
Same on my side: 

```
Could not extract html5player key: https://www.youtube.com/s/player/9b926fb0/player_ias.vflset/en_US/base.js
´´´

on YouTube ID: EzbkHy5axAQ

**Comment by mh4ck** [comment]
@fent

**Comment by sshcrack** [comment]
Up same on my side too `Could not extract html5player key: https://www.youtube.com/s/player/9b926fb0/player_ias.vflset/en_US/base.js`

**Comment by hansputera** [comment]
same

**Comment by fent** [comment]
closed by new version
