### ISSUE TITLE
use scrapestack proxy url instead of youtube url to download video

### ISSUE THREAD

**Issue by m-ilk** [fent/node-ytdl-core#628]
i am using [scrapestack](https://scrapestack.com/documentation) as proxy server. it is different from using proxy host. it requires to change the url.
for example, if i want to download video `XXXX`
i should send a request to 
```
https://api.scrapestack.com/scrape?access_key =YOUR_ACCESS_KEY&url=http://www.youtube.com/watch?v=XXXX
```
i tried to use `https-proxy-agent` in `requestOptions`, but it does not work. here is my code
```
const Agent = require('https-proxy-agent');

let agent = new Agent({
       host:`api.scrapestack.com`,
       path:`/scrape?access_key=${key}&url=https://www.youtube.com/watch?v=${videoId}`
    });
    var stream = ytdl(`${proxy}${videoId}`, { filter: 'audio', quality: 'highest'});
```
i got error:
`Status code: 400`

**Comment by fent** [comment]
Try using the [`requestOptions.transform` option](https://github.com/fent/node-miniget#api). something like

```js
ytdl(videoId, {
    requestOptions: {
        transform: (parsed) => {
            parsed.host = 'api.scrapestack.com'
            parsed.path = `/scrape?access_key=${key}&url=https://www.youtube.com/watch?v=${videoId}`
            return parsed;
        },
    },
});
```

**Comment by m-ilk** [comment]
hey fent. i tried your code. here is what i got 
```
(node:2306) UnhandledPromiseRejectionWarning: Error: Too many redirects
    at ClientRequest.<anonymous> (/Users/michaellee/Desktop/acr_template/node_modules/miniget/dist/index.js:129:42)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:632:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:501:22)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    at TLSSocket.Readable.push (_stream_readable.js:217:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```
i am using 2.1.5
