### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by TheGoobsy** [fent/node-ytdl-core#630]
Error occurs in the last minutes/seconds of a video stream using ytdl with discord.js:

```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

using following code:

```
let dispatcher = connection.play(ytdl(track.url, {filter: "audioonly"}));

dispatcher.on("error", (err) => {
        console.error("Dispatcher encountered an error:", err);
});
```

Also applies to ytdl-core-discord and only happens in the last minutes/seconds of a video stream (depends on the video length).
Also I'm pretty sure that in the last days everything worked fine.

Thank you in advance!

**Comment by fent** [comment]
ytdl-core-discord could be using an older version of the library. check the version with `npm ls ytdl-core`

**Comment by TheGoobsy** [comment]
Thank you for your response!

ytdl-core version was `2.1.3`, now it is `2.1.4`

I am also getting `Status code: 416` errors lately, also in the last minutes of a stream...

```
Error: input stream: Status code: 416
    at ClientRequest.<anonymous> (D:\coding\discord\bot\node_modules\miniget\dist\index.js:128:27)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
```

**However:** I moved the project from my windows pc to my linux server and everything **is working fine on linux**, which I find a bit confusing but whatever...

Maybe I messed up something with the dependencies on windows but I can't figure it out, the versions of ytdl-core and ytdl-core-discord should be both up to date.

**Comment by RezenDeveloper** [comment]
I am having this `Status code: 416` error as well, it only happens in the last minutes of a stream.
My ytdl-core is on version `2.1.7`.
