### ISSUE TITLE
Cannot read property 'playabilityStatus' of undefined

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#631]
```
/var/www/.../node_modules/ytdl-core/lib/util.js:435
data:    index.js:32159 -   let playability = info.playerResponse.playabilityStatus;
data:    index.js:32159 -                                         ^
data:    index.js:32159 - TypeError: Cannot read property 'playabilityStatus' of undefined
data:    index.js:32159 -     at Object.exports.playError (/var/www/.../node_modules/ytdl-core/lib/util.js:435:41)
data:    index.js:32159 -     at downloadFromInfoCallback (/var/www/.../node_modules/ytdl-core/lib/index.js:63:18)
data:    index.js:32159 -     at Immediate.<anonymous> (/var/www/.../node_modules/ytdl-core/lib/index.js:167:5)
data:    index.js:32159 -     at processImmediate (internal/timers.js:439:21)
```

Did the object changed?

**Comment by fent** [comment]
with a certain video?

**Comment by mh4ck** [comment]
I'm caching the info object while it's not expired. I just upgraded to the newest version and got a lot of this errors... so i guess the object hast updated. Is the 'player_response' still ist available? Because i use some infos out of it.

**Comment by fent** [comment]
the old versions before v2.1.3 did not contain a `playerResponse` object
