### ISSUE TITLE
Could not extract html5player key

### ISSUE THREAD

**Issue by AwesomeStickz** [fent/node-ytdl-core#637]
I'm using ytdl-core in a discord bot and I got the latest version of ytdl-core, v2.1.5

The error is:
```
Could not extract html5player key: https://www.youtube.com/s/player/4583e272/player_ias.vflset/en_US/base.js
```

It happens every time I try to play a song, and also sometimes getting this error 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at doDownload (/root/Amazing/node_modules/miniget/dist/index.js:90:28)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
The other issues posts that have been closed didn't help me really that's why posting a separate issue

**Comment by fent** [comment]
please see note at the end of the readme about using the latest version
