### ISSUE TITLE
24/7 youtube stream https://www.youtube.com/watch?v=eH7hBiY9xkg

### ISSUE THREAD

**Issue by BenasPaulikas** [fent/node-ytdl-core#64]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Video not found
    at gotConfig (/root/node_modules/ytdl-core/lib/info.js:157:14)
    at /root/node_modules/ytdl-core/lib/info.js:53:7
    at IncomingMessage.<anonymous> (/root/node_modules/ytdl-core/lib/request.js:34:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by fent** [comment]
Yep
