### ISSUE TITLE
getting Unhandled Rejection at: Promise Promise <rejected> Error: Video unavailable when calling getBasicInfo/getInfo

### ISSUE THREAD

**Issue by m-ilk** [fent/node-ytdl-core#649]
i was trying to get information of an unavailable video. using the following code. video id `05KNh4XRnKs`
```
try {

            let videoInfo = await ytdl.getBasicInfo(`https://www.youtube.com/watch?v=${videoId}`)
            console.log(videoInfo);
            if (!videoInfo) {
                throw new Error(`${videoId} is not a valid id`);
            }else{
                return {videoInfo:videoInfo};
            }
        } catch (error) {

        }
```
i was not able to catch the error, and throw Unhandled promise.
```
(node:28843) UnhandledPromiseRejectionWarning: Error: Video unavailable
at Object.exports.playError (/Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/util.js:437:12)
      at downloadFromInfoCallback (/Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/index.js:63:18)
      at /Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/index.js:23:5
      at /Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/info.js:289:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
} reason: Error: Video unavailable
    at Object.exports.playError (/Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/util.js:437:12)
    at downloadFromInfoCallback (/Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/index.js:63:18)
    at /Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/index.js:23:5
    at /Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/info.js:289:23
```
if i add a call back function. i can still get the information of that video , but i was not able to catch the `Video unavailable` error

**Comment by fent** [comment]
try updating to latest

**Comment by m-ilk** [comment]
still receiving the same exception
```
(node:31041) UnhandledPromiseRejectionWarning: Error: Video unavailable
    at Object.exports.playError (/Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/util.js:441:12)
    at downloadFromInfoCallback (/Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/index.js:57:18)
    at /Users/michaellee/Desktop/acr_template/node_modules/ytdl-core/lib/index.js:18:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31041) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by m-ilk** [comment]
sorry i missed some information above.
if i only run `ytdl.getBasicInfo`. although it does not through any exception and i was not able to catch `Video unavailable`, it works fine.
when i run the following code after `ytdl.getBasicInfo`, it starts to throw exception 
```
var stream = ytdl(videoUrl,options)
return new Promise((resolve,reject) => {
  stream.on('error',  (err) => {
            reject({code:ErrorHandle.YOUTUBE_DOWNLOAD,message:`[${videoId}] download error: ${err.message}`})
        });
  stream.on('response', (res) => {this.fetch_percentage(res)});
  stream.on('finish',  () => {resolve()});
  stream.pipe(fs.createWriteStream(saveTo));
})
```
if i put the `var stream = ytdl(videoUrl,options)` inside the promise. it works, i can catch the error without any problem.
```
return new Promise((resolve,reject) => {
        var stream = ytdl(videoUrl,options)
        stream.on('error',  (err) => {
            if (this.proxy) {
                this.proxy.blocked = true;
            }
            reject({code:ErrorHandle.YOUTUBE_DOWNLOAD,message:`[${videoId}] download error: ${err.message }`})
        });
        stream.on('response', (res) => {this.fetch_percentage(res)});
        stream.on('finish',  () => {resolve()});
        stream.pipe(fs.createWriteStream(saveTo));
    })
```
im not sure why it happened...
i think the problem solved. thank you fent

**Comment by fent** [comment]
np
