### ISSUE TITLE
secondaryResults is not iterable when calling getInfo

### ISSUE THREAD

**Issue by aidangoettsch** [fent/node-ytdl-core#654]
Calling `getInfo` with some videos results in the following error:
```
(node:61290) UnhandledPromiseRejectionWarning: TypeError: secondaryResults is not iterable
    at Object.exports.getRelatedVideos (/mnt/data/Code/Node/discord-music-bot/node_modules/ytdl-core/lib/info-extras.js:128:22)
    at gotConfig (/mnt/data/Code/Node/discord-music-bot/node_modules/ytdl-core/lib/info.js:151:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.<computed> [as getBasicInfo] (/mnt/data/Code/Node/discord-music-bot/node_modules/ytdl-core/lib/info.js:298:18)
    at async exports.getInfo (/mnt/data/Code/Node/discord-music-bot/node_modules/ytdl-core/lib/info.js:184:14)
    at async Function.exports.<computed> [as getInfo] (/mnt/data/Code/Node/discord-music-bot/node_modules/ytdl-core/lib/info.js:298:18)
    at async VoiceHandler.addTrack (/mnt/data/Code/Node/discord-music-bot/src/Modules/VoiceHandler.js:20:18)
    at async Object.exports.handler (/mnt/data/Code/Node/discord-music-bot/src/Commands/play.js:53:5
``` 

It appears #509 mentions a fix for this issue, which appears to be dependent on the mood of the YouTube API. Might be worth merging it or something similar to avoid the issue in the future.

**Comment by gdoron** [comment]
Yeah, I still see it from time to time.

**Comment by fent** [comment]
are you using a custom user-agent or proxy?

**Comment by gdoron** [comment]
Proxy, no custom user-agent.

**Comment by Drift91** [comment]
Also experienced this just now. Not using a proxy or custom user agent. I was able to download two other videos just fine and then the third one threw this error. I retried with another video to be sure I wasn't being rate-limited by YouTube and it worked fine.

**Comment by skick1234** [comment]
`secondaryResults` is undefined in some videos that caused this error. I added `if (!secondaryResults) throw ""` in `info-extras.js` after line 138 to fix that issue temporarily. But I have no idea to get related videos. Tested video id: NeQM1c-XCDc

**Comment by fent** [comment]
this has been happening during daily tests too

https://github.com/fent/node-ytdl-core/runs/936410701?check_suite_focus=true

will look into it

**Comment by vegidio** [comment]
I found this problem today happening in the webserver that I hosted on Digital Ocean. I thought it was a problem in my code, but I just ran the webserver locally in my machine and it works. I'm afraid that YouTube is implementing some sort of rate limit 😟

**Comment by vegidio** [comment]
Some more info: 3 hours after my previous message here, the code that couldn't extract info running in my webserver is suddenly working now. I didn't change anything in my code.

**Comment by gdoron** [comment]
I know the author of #509, he's a good guy, worth merging his stuff 😉
