### ISSUE TITLE
Error: input stream: Video unavailable

### ISSUE THREAD

**Issue by ifaisalqz** [fent/node-ytdl-core#658]
- [ ] ytdl-core latest

Hi, I keep getting this error:
`Error: input stream: Video unavailable
    at Object.exports.playError (/home/nez/node_modules/ytdl-core/lib/util.js:437:12)
    at downloadFromInfoCallback (/home/nez/node_modules/ytdl-core/lib/index.js:63:18)
    at /home/nez/node_modules/ytdl-core/lib/index.js:23:5
    at /home/nez/node_modules/ytdl-core/lib/info.js:288:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
`

With some youtube url Like : [https://www.youtube.com/watch?v=ele2DMU49Jk](url)

**Comment by justsomederpystuff** [comment]
The video is only available in specific countries. You'll have to use a proxy to bypass this.

**Comment by ifaisalqz** [comment]
Okay thank you so much.
