### ISSUE TITLE
crash unexpectedly, log attached

### ISSUE THREAD

**Issue by yxwu** [fent/node-ytdl-core#662]
My app crashed several times today, seems related with ytpl. Please see the log attached below:
```
/app/node_modules/ytpl/lib/util.js:22
    title: exports.removeHtml(importantTxt.match(PLAYLIST_NAME_REGEXP)[1]),
                                                                      ^

TypeError: Cannot read property '1' of null
    at Object.exports.getGeneralInfo (/srv/app/node_modules/ytpl/lib/util.js:22:71)
    at IncomingMessage.<anonymous> (/srv/app/node_modules/ytpl/lib/firstpage.js:30:29)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by fent** [comment]
the stack trace shows this is coming from ytpl

**Comment by yxwu** [comment]
oh, my bad
