### ISSUE TITLE
"lines matching original stack trace" Error Please Help!

### ISSUE THREAD

**Issue by softwebtuts** [fent/node-ytdl-core#694]
### I am getting this error! Please solve my issue by leaving your suggestions on what should I do now.

```
Audio  | 109.68% processedevents.js:292.80MB).
      throw er; // Unhandled 'error' event8MB).
      ^| processing frame 3577 (at 29.16 fps => 1.15x).
running for: 2.15 Minutes.
Error: Status code: 416
    at ClientRequest.<anonymous> (C:\Users\Muzammil\Desktop\NodeJs\YTDL\node_modules\miniget\dist\index.js:156:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
Emitted 'error' event on PassThrough instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at PassThrough.onerror (_stream_readable.js:752:7)
    at PassThrough.emit (events.js:315:20)
    at PassThrough.<anonymous> (C:\Users\Muzammil\Desktop\NodeJs\YTDL\node_modules\ytdl-core\lib\index.js:96:16)
    at PassThrough.emit (events.js:327:22)
    at ClientRequest.<anonymous> (C:\Users\Muzammil\Desktop\NodeJs\YTDL\node_modules\miniget\dist\index.js:161:28)
    at Object.onceWrapper (events.js:422:26)
    [... lines matching original stack trace ...]
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
```

**Comment by Cyanitem** [comment]
https://github.com/fent/node-ytdl-core/issues/659
