### ISSUE TITLE
"ERR_STREAM_WRITE_AFTER_END" Error Please Help

### ISSUE THREAD

**Issue by softwebtuts** [fent/node-ytdl-core#695]
I am getting this issue while downloading videos please suggest me the solution.

```
Audio  | 91.20% processed events.js:29280MB).
      throw er; // Unhandled 'error' event8MB).
      ^| processing frame 3136 (at 18.16 fps => 0.713x).
running for: 3.00 Minutes.
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:266:14)
    at PassThrough.Writable.write (_stream_writable.js:315:5)
    at IncomingMessage.ondata (_stream_readable.js:716:22)
    at IncomingMessage.emit (events.js:327:22)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at IncomingMessage.Readable.push (_stream_readable.js:212:10)
    at HTTPParser.parserOnBody (_http_common.js:132:24)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
Emitted 'error' event on PassThrough instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at PassThrough.onerror (_stream_readable.js:752:7)
    at PassThrough.emit (events.js:315:20)
    at PassThrough.<anonymous> (C:\Users\Muzammil\Desktop\NodeJs\YTDL\node_modules\ytdl-core\lib\index.js:96:16)
    at PassThrough.emit (events.js:327:22)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at writeAfterEnd (_stream_writable.js:268:3)
    at PassThrough.Writable.write (_stream_writable.js:315:5)
    at IncomingMessage.ondata (_stream_readable.js:716:22)
    at IncomingMessage.emit (events.js:327:22) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

**Comment by fent** [comment]
is this from running the ffmpeg.js example?

**Comment by softwebtuts** [comment]
Yes, please solve this issue. I did my best but sometimes this happens and sometimes not I don't know what actually the issue is.

Basically I am making youtube video downloader app and using FFmpeg to merge audio and video to make it possible to download it in different formats.

**Comment by fent** [comment]
I'm unable to reproduce this
