### ISSUE TITLE
Status Code: 429

### ISSUE THREAD

**Issue by isuckatprogram** [fent/node-ytdl-core#700]
So, I have a discord bot that plays music so I tried playing 8D audio but it didn't work. I tried playing this [song](https://www.youtube.com/watch?v=nAlteS546HU&ab_channel=Revo-luution). I get an Error Status Code: 429 on my Heroku logs. 

Error:

```
2020-09-05T17:16:29.273604+00:00 app[worker.1]: (node:34) UnhandledPromiseRejectionWarning: Error: Status code: 429
2020-09-05T17:16:29.273625+00:00 app[worker.1]:     at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:150:31)
2020-09-05T17:16:29.273626+00:00 app[worker.1]:     at Object.onceWrapper (events.js:422:26)
2020-09-05T17:16:29.273626+00:00 app[worker.1]:     at ClientRequest.emit (events.js:315:20)
2020-09-05T17:16:29.273627+00:00 app[worker.1]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
2020-09-05T17:16:29.273627+00:00 app[worker.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
2020-09-05T17:16:29.273628+00:00 app[worker.1]:     at TLSSocket.socketOnData (_http_client.js:469:22)
2020-09-05T17:16:29.273629+00:00 app[worker.1]:     at TLSSocket.emit (events.js:315:20)
2020-09-05T17:16:29.273629+00:00 app[worker.1]:     at addChunk (_stream_readable.js:295:12)
2020-09-05T17:16:29.273629+00:00 app[worker.1]:     at readableAddChunk (_stream_readable.js:271:9)
2020-09-05T17:16:29.273630+00:00 app[worker.1]:     at TLSSocket.Readable.push (_stream_readable.js:212:10)
```

**Comment by isuckatprogram** [comment]
Haha, I'm the #700 issue post, which is a good thing but a bad thing at the same time.

**Comment by TimeForANinja** [comment]
even worse if there's already an issue open for the same error
https://github.com/fent/node-ytdl-core/issues/635

**Comment by isuckatprogram** [comment]
oof

**Comment by isuckatprogram** [comment]
should I close this or?

**Comment by TimeForANinja** [comment]
if you feel like the issue represents your problem - a single issue should be enough
you can always add to an existing issue via comments

**Comment by fent** [comment]
dupe, look in https://github.com/fent/node-ytdl-core/issues/635 for possible workarounds. the main one being using a cookie.
