### ISSUE TITLE
problem with Error: Could not find player config

### ISSUE THREAD

**Issue by K1NEX** [fent/node-ytdl-core#738]
(node:3472) UnhandledPromiseRejectionWarning: Error: Could not find player config
    at exports.getBasicInfo (C:\Users\Timur\Desktop\R-Music\node_modules\discord-ytdl-core\node_modules\ytdl-core\lib\info.js:59:13)
    at async exports.getFullInfo (C:\Users\Timur\Desktop\R-Music\node_modules\discord-ytdl-core\node_modules\ytdl-core\lib\info.js:187:14)
    at async Object.exports.<computed> [as getFullInfo] (C:\Users\Timur\Desktop\R-Music\node_modules\discord-ytdl-core\node_modules\ytdl-core\lib\info.js:296:18)
(node:3472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

updated to the latest intel-core, still the same issue

**Comment by fent** [comment]
you're using discord-ytdl-core, which is using an older version of ytdl-core. look at the bottom of the readme for instructions on pudating ytdl-core within another dependency

**Comment by mirsella** [comment]
had the same error with ytdl-core, ran `npm update` and it was good
