### ISSUE TITLE
Error: input stream: Could not find player config

### ISSUE THREAD

**Issue by thestevexyz** [fent/node-ytdl-core#757]
Hello, 

I'm using ytdl-core in my Discord bot which worked fine for a long time. 
Since Youtube must've changed something many services like NewPipe didn't work anymore. For example NewPipe had the exact same error message saying that the player config couldn't be found and in their latest release yesterday, they finally fixed it. A link to their issue can be found [here](https://github.com/TeamNewPipe/NewPipe/issues/4572). Maybe it's easier for you to fix it given this.

The exception occurres in `ytdl-core/lib/info.js` at `exports.getBasicInfo`. So it's most likely it's a problem with ytdl-core. Here's the stacktrace:
` Error: input stream: Could not find player config
    at exports.getBasicInfo (/home/discord/bots/symphony/node_modules/ytdl-core/lib/info.js:59:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.exports.<computed> [as getBasicInfo] (/home/discord/bots/symphony/node_modules/ytdl-core/lib/info.js:297:18)
    at async exports.getFullInfo (/home/discord/bots/symphony/node_modules/ytdl-core/lib/info.js:188:14)
    at async Object.exports.<computed> [as getFullInfo] (/home/discord/bots/symphony/node_modules/ytdl-core/lib/info.js:297:18)`

Running latest ytdl-core on:
Node v12.14.0 with NPM v6.13.4 on Ubuntu 18.04

**Comment by IH4xx3R** [comment]
Update to version 4.0.0 -> check your package.json -> "ytdl-core": "^4.0.0" -> run npm install

**Comment by thestevexyz** [comment]
Thank you, this resolved the problem.
