### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received null On V4.0.1

### ISSUE THREAD

**Issue by MatteZ02** [fent/node-ytdl-core#759]
Full error stack:
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received null
    at validateString (internal/validators.js:124:11)
    at Url.parse (url.js:159:3)
    at urlParse (url.js:154:13)
    at Url.resolve (url.js:667:29)
    at Object.urlResolve [as resolve] (url.js:663:40)
    at exports.getInfo (C:\Users\matte\Documents\GitHub\Musix\node_modules\ytdl-core\lib\info.js:260:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Map.getOrSet (C:\Users\matte\Documents\GitHub\Musix\node_modules\ytdl-core\lib\cache.js:24:19)
    at async Object.default_1 [as handleVideo] (C:\Users\matte\Documents\GitHub\Musix\build\struct\functions\handleVideo.js:12:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}

I did some digging to the code and seems like on line 121 of info.js the const getHTML5player returns null due to html5playerRes being null.
I can do some further debugging if thats needed.

**Comment by ErikSzabo** [comment]
Looks like this regex change solved the entire problem for me:
```js
const getHTML5player = body => {
  let html5playerRes = /"jsUrl":"([^"]+)"/.exec(body);
  return html5playerRes ? html5playerRes[1] : null;
};
```
The original regex which searches for a script tag is sometimes failing beacuse the response does not include the specific script tag.

**Comment by ultrasamad** [comment]
I'm also getting this error all of a sudden. I don't used to get it

**Comment by fent** [comment]
> Looks like this regex change solved the entire problem for me:

thanks for this

**Comment by MatteZ02** [comment]
I'll have to try that regex change. If it works like a charm might do a pr to fix it.
