### ISSUE TITLE
Error parsing info still present

### ISSUE THREAD

**Issue by hypo-thesis** [fent/node-ytdl-core#762]
version :  "ytdl-core": "3.4.2" 
 node : 15.0.1

```
/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/info.js:75
      throw Error(`Error parsing info: ${err.message}`);
            ^

Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/info.js:75:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async exports.getBasicInfo (/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/info.js:84:22)
    at async Map.getOrSet (/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/info.js:226:14)
    at async Map.getOrSet (/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/cache.js:24:19)
Emitted 'error' event on PassThrough instance at:
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

How to resolve this issue? It appears randomly.

**Comment by skick1234** [comment]
You should check what's the latest version first 🤔

**Comment by hypo-thesis** [comment]
> You should check what's the latest version first 🤔

Upgraded to 4.0.2 and will watch it. Closed for now. ty.
