### ISSUE TITLE
The "url" argument must be of type string. Received undefined. help pls

### ISSUE THREAD

**Issue by LiseQiu** [fent/node-ytdl-core#768]
### So im making an discord music bot and i can't use url in this situation :
      const songInfo = await ytdl.getInfo(args[1]);
      const song = {
       title: songInfo.title,
       url: songInfo.video_url,
      };
### any clues how can i repair it ? (not good english sorry in meaning of typing not translate) error log lower.
(node:13520) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at Object.exports.getURLVideoID (C:\Users\Agnieszka Hałuszczak\bot-lis\node_modules\ytdl-core\lib\url-utils.js:30:22)
    at Object.exports.getVideoID (C:\Users\Agnieszka Hałuszczak\bot-lis\node_modules\ytdl-core\lib\url-utils.js:63:20)
    at Function.exports.<computed> [as getInfo] (C:\Users\Agnieszka Hałuszczak\bot-lis\node_modules\ytdl-core\lib\info.js:364:23)
    at Client.<anonymous> (C:\Users\Agnieszka Hałuszczak\bot-lis\src\bot.js:43:35)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (C:\Users\Agnieszka Hałuszczak\bot-lis\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Agnieszka Hałuszczak\bot-lis\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)      
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or 
by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` 
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by deniscerri** [comment]
update ytdl-core 
npm i ytdl-core@latest

**Comment by fent** [comment]
stack trace shows the error coming from calling `getInfo()` with an `undefined` url
