### ISSUE TITLE
Problems to play videos

### ISSUE THREAD

**Issue by LuaaDev** [fent/node-ytdl-core#785]
So i have this problem for more than a day and it is the 429 error code, I have the latest version of ytdl-core, but the error still happens
```
MinigetError: input stream: Status code: 429
    at ClientRequest.<anonymous> (/home/container/node_modules/ytdl-core/node_modules/miniget/dist/index.js:190:31)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:602:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:475:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  statusCode: 429
}
```

**Comment by MGPlayzYT** [comment]
This error happens when YouTube ratelimits you, you can prevent this through cookies.
Example: https://github.com/fent/node-ytdl-core/blob/master/example/cookies.js

**Comment by LuaaDev** [comment]
Ok, thanks

**Comment by fent** [comment]
look through https://github.com/fent/node-ytdl-core/issues/635 for more possible solutions
