### ISSUE TITLE
4.1.0 - Unable to retrieve video metadata

### ISSUE THREAD

**Issue by EmeraldTools10** [fent/node-ytdl-core#795]
```
Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (C:\Users\ARH07\OneDrive\Desktop\Discord Bots\Python\Python\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\info.js:75:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async exports.getBasicInfo (C:\Users\ARH07\OneDrive\Desktop\Discord Bots\Python\Python\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\info.js:84:22)
    at async Map.getOrSet (C:\Users\ARH07\OneDrive\Desktop\Discord Bots\Python\Python\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\cache.js:24:19)
    at async exports.getInfo (C:\Users\ARH07\OneDrive\Desktop\Discord Bots\Python\Python\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\info.js:226:14)
    at async Map.getOrSet (C:\Users\ARH07\OneDrive\Desktop\Discord Bots\Python\Python\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\cache.js:24:19)
    at async download (C:\Users\ARH07\OneDrive\Desktop\Discord Bots\Python\Python\node_modules\ytdl-core-discord\index.js:26:15)
    at async play (C:\Users\ARH07\OneDrive\Desktop\Discord Bots\Python\Python\Utilities\play.js:24:18)
```

I've tried reinstalling , switching to other versions and still the same issue
Has anyone got anything?

**Comment by Synkky** [comment]
That stacktrace tells me you're using `ytdl-core-discord`, not `ytdl-core` so how could you have possibly updated to 4.1.0 if you're using an **entirely different package**?

**Comment by EmeraldTools10** [comment]
> That stacktrace tells me you're using `ytdl-core-discord`, not `ytdl-core` so how could you have possibly updated to 4.1.0 if you're using an **entirely different package**?

I installed 4.1.0 independently , which is in the dependencies for ytdl-core-discord

**Comment by UnderMaksDev** [comment]
Im also have ir
`Error: Error parsing info: Unable to retrieve video metadata
at getWatchPage (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:75:13)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async exports.getBasicInfo (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:84:22)
at async Map.getOrSet (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
at async exports.getInfo (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:226:14)
at async Map.getOrSet (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
at async download (/home/container/node_modules/ytdl-core-discord/index.js:26:15)
at async play (/home/container/include/play.js:36:18)`

**Comment by fent** [comment]
> That stacktrace tells me you're using `ytdl-core-discord`, not `ytdl-core` so how could you have possibly updated to 4.1.0 if you're using an **entirely different package**?

yep, the stack trace also points to an outdated version of `info.js`. ytdl-core-discord is using an older version of ytdl-core

**Comment by UnderMaksDev** [comment]
> > That stacktrace tells me you're using `ytdl-core-discord`, not `ytdl-core` so how could you have possibly updated to 4.1.0 if you're using an **entirely different package**?
> 
> yep, the stack trace also points to an outdated version of `info.js`. ytdl-core-discord is using an older version of ytdl-core

So...what i can do with that? Why EvoBot works, but my not

**Comment by fent** [comment]
look at the bottom of the readme on how to install the latest version
