### ISSUE TITLE
Miniget error!

### ISSUE THREAD

**Issue by DocelaEpickyK3BA** [fent/node-ytdl-core#798]
### After installing new version of ytdl-core it throws this error

```
MinigetError: Status code: 403
0|musiccloud  |     at ClientRequest.<anonymous> (/root/muzikovymrak/node_modules/miniget/dist/index.js:196:27)
0|musiccloud  |     at Object.onceWrapper (events.js:421:26)
0|musiccloud  |     at ClientRequest.emit (events.js:314:20)
0|musiccloud  |     at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
0|musiccloud  |     at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
0|musiccloud  |     at TLSSocket.socketOnData (_http_client.js:474:22)
0|musiccloud  |     at TLSSocket.emit (events.js:314:20)
0|musiccloud  |     at addChunk (_stream_readable.js:297:12)
0|musiccloud  |     at readableAddChunk (_stream_readable.js:272:9)
0|musiccloud  |     at TLSSocket.Readable.push (_stream_readable.js:213:10)
0|musiccloud  |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
0|musiccloud  |   statusCode: 403
0|musiccloud  | }
0|musiccloud  | Error: Status code: 403
0|musiccloud  | Error: Status code: 403
0|musiccloud  | abort(Error: Status code: 403). Build with -s ASSERTIONS=1 for more info.
0|musiccloud  | /root/muzikovymrak/node_modules/opusscript/build/opusscript_native_wasm.js:8
0|musiccloud  | var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(ke
```

**Comment by fent** [comment]
any idea what url or video this happens with? or does it happen when ytdl-core is first loaded?

**Comment by mh4ck** [comment]
```
/var/www/---/node_modules/miniget/dist/index.js:196
                let err = new Miniget.MinigetError('Status code: ' + res.statusCode, res.statusCode);
                          ^

MinigetError: Status code: 403
    at ClientRequest.<anonymous> (/var/www/---/node_modules/miniget/dist/index.js:196:27)
    at Object.onceWrapper (node:events:483:26)
    at ClientRequest.emit (node:events:376:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:660:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:126:17)
    at TLSSocket.socketOnData (node:_http_client:526:22)
    at TLSSocket.emit (node:events:376:20)
    at addChunk (node:internal/streams/readable:305:12)
    at readableAddChunk (node:internal/streams/readable:280:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:219:10) {
  statusCode: 403
}
``` 
Same on my side...  seems to happen at it first load - but it also would be nice to catch these errors and reach them through to the getInfo catch..

**Comment by BearTS** [comment]
I am getting the same error
```
          let err = new Miniget.MinigetError('Status code: ' + res.statusCode, res.statusCode);
                          ^
MinigetError: Status code: 403
    at ClientRequest.<anonymous> (/home/container/node_modules/miniget/dist/index.js:196:27)
    at Object.onceWrapper (node:events:483:26)
    at ClientRequest.emit (node:events:376:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:648:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:126:17)
    at TLSSocket.socketOnData (node:_http_client:514:22)
    at TLSSocket.emit (node:events:376:20)
    at addChunk (node:internal/streams/readable:311:12)
    at readableAddChunk (node:internal/streams/readable:286:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:225:10) {
  statusCode: 403
}
```

**Comment by fent** [comment]
> Same on my side... seems to happen at it first load - but it also would be nice to catch these errors and reach them through to the getInfo catch..

so it only happens once on the first ytdl call? if so, most likely it's the request to github to check for updates. 403 could mean the request is being made too often. we could have the request be catchable, but also, ytdl could catch the error and then print nothing.

**Comment by russtee** [comment]
is for the following url: https://api.github.com/repos/fent/node-ytdl-core/releases/latest 
All the other calls seem fine.

**Comment by fent** [comment]
what kind of app do you have? is it restarted a lot? the github public api rate limit is usually in the thousands per hour. this request is only made at the beginning of the application start, and then every 12 hours

**Comment by russtee** [comment]
It's a shell script. When running at high concurrency it could potentially hit thousands per hour but that would be unusual. When using YTDL_NO_UPDATE it works fine.

**Comment by BearTS** [comment]
any fix yet?
