### ISSUE TITLE
Unable to retrieve video metadata

### ISSUE THREAD

**Issue by Pedro9700** [fent/node-ytdl-core#799]
![image](https://user-images.githubusercontent.com/29014242/100624241-1f77a380-331b-11eb-8365-d54c550572a5.png)
I get this error every time i try to play a music.
versions:
node 15.3.0
npm 7.0.14
ytdl-core 4.1.1
ytdl-core-discord 1.2.4

**Comment by redbrain** [comment]
ytdl-core-discord is using its own version of ytdl-core (3.4.2) as shown by `npm ls ytdl-core`. you'd need to get an up-to-date fork of ytdl-core-discord, such as https://github.com/MGPlayzYT/ytdl-core-discord

**Comment by Pedro9700** [comment]
Is that whats problably causing the issue?
thanks for the super fast response btw 👍

**Comment by Pedro9700** [comment]
I know this is already outside of ytdl , but i followed your suggestion of installing MGPlayzYT ytdl-core-discord and now im getting this:
![image](https://user-images.githubusercontent.com/29014242/100625790-de808e80-331c-11eb-824f-33ab2fe976d5.png)
Thanks in advance :)

**Comment by mirsella** [comment]
same but for ytdl-core not the discord version.
```
/run/media/mirsella/ssd/dev/tutubedl/node_modules/.pnpm/ytdl-core@3.4.2/node_modules/ytdl-core/lib/info.js:75
      throw Error(`Error parsing info: ${err.message}`);
            ^

Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (/run/media/mirsella/ssd/dev/tutubedl/node_modules/.pnpm/ytdl-core@3.4.2/node_modules/ytdl-core/lib/info.js:75:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async exports.getBasicInfo (/run/media/mirsella/ssd/dev/tutubedl/node_modules/.pnpm/ytdl-core@3.4.2/node_modules/ytdl-core/lib/info.js:84:22)
    at async Map.getOrSet (/run/media/mirsella/ssd/dev/tutubedl/node_modules/.pnpm/ytdl-core@3.4.2/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/run/media/mirsella/ssd/dev/tutubedl/node_modules/.pnpm/ytdl-core@3.4.2/node_modules/ytdl-core/lib/info.js:226:14)
    at async Map.getOrSet (/run/media/mirsella/ssd/dev/tutubedl/node_modules/.pnpm/ytdl-core@3.4.2/node_modules/ytdl-core/lib/cache.js:24:19)
Emitted 'error' event on PassThrough instance at:
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
 ERROR  Command failed with exit code 1.
```

**Comment by redbrain** [comment]
That's also an issue with ytdl-core-discord. Again, I wouldn't use that library, and instead just use ytdl-core.
