### ISSUE TITLE
add support for scheme https://www.youtube.com/v/

### ISSUE THREAD

**Issue by kilianc** [fent/node-ytdl-core#80]
I currently get an error but it shouldn't be hard to add a new regexp

<details>
  <pre><code>
Error: No video id found: https://www.youtube.com/v/cumTHJHoHIM
    at Object.exports.getVideoID (/Volumes/WS/apps/nvm/versions/node/v6.2.2/lib/node_modules/ytdl/node_modules/ytdl-core/lib/util.js:222:11)
    at getInfo (/Volumes/WS/apps/nvm/versions/node/v6.2.2/lib/node_modules/ytdl/node_modules/ytdl-core/lib/info.js:39:17)
    at ytdl (/Volumes/WS/apps/nvm/versions/node/v6.2.2/lib/node_modules/ytdl/node_modules/ytdl-core/lib/index.js:18:3)
    at Object.<anonymous> (/Volumes/WS/apps/nvm/versions/node/v6.2.2/lib/node_modules/ytdl/bin/ytdl.js:240:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)</code></pre>
</details>

**Comment by kilianc** [comment]
```js
exports.getVideoID = function(link) {
  var linkParsed = url.parse(link, true);
  if (linkParsed.hostname === 'youtu.be') {
    return linkParsed.pathname.slice(1);
  }
  if (/www\.youtube\.com\/v\//.test(linkParsed.path)) {
    return linkParsed.path.split('/').pop();
  }
  if (linkParsed.query.v) {
    return linkParsed.query.v;
  }
  throw new Error('No video id found: ' + link);
};
```
