### ISSUE TITLE
Metadata error

### ISSUE THREAD

**Issue by Jerlag01** [fent/node-ytdl-core#813]
Hi, I'm having the following issue when my discord bot is being used to play music:

It's returning this: Error: Error parsing info: Unable to retrieve video metadata

The following message in console that relates to it:

Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:75:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getBasicInfo (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:84:22)
    at async Map.getOrSet (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:226:14)
    at async Map.getOrSet (/home/container/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
    at async download (/home/container/node_modules/ytdl-core-discord/index.js:26:15)
    at async Object.play (/home/container/include/play.js:30:18)

Running ytdl-core 4.0.0.

**Comment by Synkky** [comment]
You're using `ytdl-core-discord`, which uses a deprecated version of `ytdl-core`.
Just use an up-to-date `ytdl-core` directly instead.

**Comment by Jerlag01** [comment]
Has been solved after updating.

**Comment by AryanChaudhary24121** [comment]
> Has been solved after updating.

How do i update ytdl core?
