### ISSUE TITLE
Audio only and then()

### ISSUE THREAD

**Issue by r0hin** [fent/node-ytdl-core#820]
Hi i'm trying to download a video's audio stream only instead of converting it to mp3 after downloading as video. So far I just have this
```
ytdl('http://www.youtube.com/watch?v=' + id, { filter: 'audioonly', quality: 'lowestaudio' }).pipe(fs.createWriteStream('/tmp/file.mp3')).then(() => {}
```
But there is an error:
(node:13846) UnhandledPromiseRejectionWarning: TypeError: ytdl(...).pipe(...).then is not a function
    at .../Desktop/F/Node/heroku/index.js:46:143
    at Layer.handle [as handle_request] (.../Desktop/F/Node/heroku/node_modules/express/lib/router/layer.js:95:5)
    at next (.../Desktop/F/Node/heroku/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (.../Desktop/F/Node/heroku/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (.../Desktop/F/Node/heroku/node_modules/express/lib/router/layer.js:95:5)
    at .../Desktop/F/Node/heroku/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (.../Desktop/F/Node/heroku/node_modules/express/lib/router/index.js:335:12)
    at next (.../Desktop/F/Node/heroku/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (.../Desktop/F/Node/heroku/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:314:20)

Thank you so much!

**Comment by Synkky** [comment]
Read. The. Docs. -> https://github.com/fent/node-ytdl-core#ytdlurl-options
`ytdl` does not return a Promise, it returns a **readable stream**, so obviously making a `then` call is just plain wrong

**Comment by r0hin** [comment]
ah. I don't have experience with readable streams. Do you know any way to do things after the stream is finished? Thanks so much!

**Comment by TimeForANinja** [comment]
https://nodejs.org/api/stream.html#stream_event_close
