### ISSUE TITLE
Error: No video id found

### ISSUE THREAD

**Issue by MortBlox** [fent/node-ytdl-core#844]
Hey! I followed a YouTuber named "Coltz"'s tutorial about making a discord music bot, the issue is, everytime I try to play music, it keeps giving me the same error, please help if you can!
`Error: No video id found: its raining tacos
    at Object.exports.getURLVideoID (C:\Users\Omar\Desktop\Discord Bots\SMPBot\node_modules\ytdl-core\lib\url-utils.js:39:11)
    at Object.exports.getVideoID (C:\Users\Omar\Desktop\Discord Bots\SMPBot\node_modules\ytdl-core\lib\url-utils.js:63:20)
    at Function.exports.<computed> [as getInfo] (C:\Users\Omar\Desktop\Discord Bots\SMPBot\node_modules\ytdl-core\lib\info.js:469:23)
    at ytdl (C:\Users\Omar\Desktop\Discord Bots\SMPBot\node_modules\ytdl-core\lib\index.js:19:8)
    at Object.run (C:\Users\Omar\Desktop\Discord Bots\SMPBot\src\commands\play.js:40:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: No video id found: dream speedrun muusic
    at Object.exports.getURLVideoID (C:\Users\Omar\Desktop\Discord Bots\SMPBot\node_modules\ytdl-core\lib\url-utils.js:39:11)
    at Object.exports.getVideoID (C:\Users\Omar\Desktop\Discord Bots\SMPBot\node_modules\ytdl-core\lib\url-utils.js:63:20)
    at Function.exports.<computed> [as getInfo] (C:\Users\Omar\Desktop\Discord Bots\SMPBot\node_modules\ytdl-core\lib\info.js:469:23)
    at ytdl (C:\Users\Omar\Desktop\Discord Bots\SMPBot\node_modules\ytdl-core\lib\index.js:19:8)
    at Object.run (C:\Users\Omar\Desktop\Discord Bots\SMPBot\src\commands\play.js:40:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by redbrain** [comment]
You can't pass a search term to ytdl. Either give it a YouTube link or turn the search term into a URL with another library such as ytsr.

**Comment by MortBlox** [comment]
Thanks!
