### ISSUE TITLE
UnrecoverableError: input stream

### ISSUE THREAD

**Issue by Safoide** [fent/node-ytdl-core#921]
UnrecoverableError: input stream:
    at Object.exports.playError (/root/BOTPARAMONOLOCO/node_modules/ytdl-core/lib/utils.js:124:12)
    at validate (/root/BOTPARAMONOLOCO/node_modules/ytdl-core/lib/info.js:53:25)
    at pipeline (/root/BOTPARAMONOLOCO/node_modules/ytdl-core/lib/info.js:175:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async exports.getBasicInfo (/root/BOTPARAMONOLOCO/node_modules/ytdl-core/lib/info.js:62:14)

This only happened a few times, but my bot stays on the voicechannel and i only can kick him before using it again.

**Comment by Zigecek** [comment]
I'm getting this error too, it comes with new update.

**Comment by TimeForANinja** [comment]
> I'm getting this error too, it comes with new update.

which update exactly?
and does rolling back resolve the issue?

**Comment by Nico-ITA** [comment]
yes mee to on last update

**Comment by Zigecek** [comment]
> > I'm getting this error too, it comes with new update.
> 
> which update exactly?
> and does rolling back resolve the issue?

Idk if it comes with 4.7.1 or 4.8.0 but if I degrade to 4.7.0 it works fine without any errors.

**Comment by TimeForANinja** [comment]
@Zigecek can you elaborate / show how you use the library?
