### ISSUE TITLE
i want youtube mp3 file for my discord bot using ffmpeg

### ISSUE THREAD

**Issue by kessanro** [fent/node-ytdl-core#94]
i want youtube mp3 file for my discord bot using ffmpeg everytime i try it crahses the bot and i need help
with this

**Comment by ArsenArsen** [comment]
I am pretty sure that if you're using Eris you could just give it the stream and it would work? Not completly sure.

**Comment by kessanro** [comment]
im using discordie

**Comment by ArsenArsen** [comment]
I personally use Eris, so sorry, I'm no good. Try the [Discord API](https://discord.gg/discord-api) server.

**Comment by fent** [comment]
If you want the audio only, there is a filter `audioonly` you can give in the [options](https://github.com/fent/node-ytdl-core#ytdlurl-options).

If you specifically want the mp3 format, [here's](https://github.com/fent/node-ytdl-core/blob/master/example/ffmpeg.js) an example of joining two videos with ffmpeg. Not the same, but it could get you where you want.

I may put more examples there at some point on converting videos to other video/audio formats.

**Comment by kessanro** [comment]
got this error
`var audioOutput = path.resolve(__dirname, 'sound.mp3');
                       ^

ReferenceError: path is not defined
    at DiscordieDispatcher.client.Dispatcher.on.err (/var/www/html/bot/bot.js:136:24)
    at emitOne (events.js:96:13)
    at DiscordieDispatcher.emit (events.js:188:7)
    at DiscordieDispatcher.emit (/var/www/html/bot/node_modules/discordie/lib/core/DiscordieDispatcher.js:37:16)
    at Discordie.handler (/var/www/html/bot/node_modules/discordie/lib/networking/messages/gateway/message_create.js:12:19)
    at Discordie.processMessage (/var/www/html/bot/node_modules/discordie/lib/core/MessageHandlerCache.js:11:55)
    at MessageHandlerCache.processGatewayMessage (/var/www/html/bot/node_modules/discordie/lib/core/MessageHandlerCache.js:53:27)
    at DiscordieDispatcher.Dispatcher.on.e (/var/www/html/bot/node_modules/discordie/lib/index.js:82:19)
    at emitOne (events.js:101:20)
    at DiscordieDispatcher.emit (events.js:188:7)
`

**Comment by ArsenArsen** [comment]
@kessanro add a const to your top so it imports the path.
```js
const path = require('path');
```

Here is a reference: https://nodejs.org/api/path.html

**Comment by kessanro** [comment]
ok

**Comment by kessanro** [comment]
more errors 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: No formats found with custom filter
    at Object.exports.chooseFormat (/var/www/html/bot/node_modules/ytdl-core/lib/util.js:112:14)
    at downloadFromInfoCallback (/var/www/html/bot/node_modules/ytdl-core/lib/index.js:43:21)
    at /var/www/html/bot/node_modules/ytdl-core/lib/index.js:24:5
    at /var/www/html/bot/node_modules/ytdl-core/lib/info.js:198:9
    at checkDone (/var/www/html/bot/node_modules/ytdl-core/lib/util.js:312:7)
    at Object.parser.onend (/var/www/html/bot/node_modules/ytdl-core/lib/info.js:276:31)
    at emit (/var/www/html/bot/node_modules/sax/lib/sax.js:640:35)
    at end (/var/www/html/bot/node_modules/sax/lib/sax.js:683:5)
    at Object.write (/var/www/html/bot/node_modules/sax/lib/sax.js:991:14)
    at Object.close (/var/www/html/bot/node_modules/sax/lib/sax.js:157:38)

**Comment by kessanro** [comment]
got it working
