### ISSUE TITLE
MinigetError: input stream: Status code: 404

### ISSUE THREAD

**Issue by Dxngaa** [fent/node-ytdl-core#943]
MinigetError: input stream: Status code: 404
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  statusCode: 404
}

- What can I do to solve this as soon as possible? Yesterday it was working correctly.

**Comment by Dxngaa** [comment]
I have been researching and this error is due to YouTube having changed API. It is time to be patient.

**Comment by TimeForANinja** [comment]
Opening an Issue for API-Changes is fine
Problem is we already have one here https://github.com/fent/node-ytdl-core/issues/939
so closing it was good 😉
