### ISSUE TITLE
Does not work any more

### ISSUE THREAD

**Issue by trinhvanbien** [fent/node-ytdl-core#954]
(node:40343) UnhandledPromiseRejectionWarning: Error: Status code: 404
    at ClientRequest.<anonymous> (/Users/mac/node_modules/ytdl-core/node_modules/miniget/dist/index.js:210:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
(node:40343) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40343) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TimeForANinja** [comment]
you should include a description of your problem
not just the issue template...

**Comment by trinhvanbien** [comment]
> you should include a description of your problem
> not just the issue template...

updated

**Comment by envythegreat** [comment]
I'm getting the same problem as him please any idea

`(node:6212) UnhandledPromiseRejectionWarning: Error: Status code: 404
    at ClientRequest.<anonymous> (C:\Users\cosmi\Desktop\cosmic\myaudioplayer\backend\node_modules\miniget\src\index.ts:257:19)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Zeroknights16** [comment]
I think the problem is that youtube updated their api again.

**Comment by Porama6400** [comment]
I have the exact same problem

**Comment by TimeForANinja** [comment]
closing as duplicate of https://github.com/fent/node-ytdl-core/issues/939
wait for the next ytdl-core update or checkout https://github.com/fent/node-ytdl-core/pull/938

**Comment by CrypticMrDark** [comment]
You still has 404 error then there are some temporary fix. 
Discord DM me: Mr.Dark#3119

**Comment by mh4ck** [comment]
> You still has 404 error then there are some temporary fix.
> Discord DM me: Mr.Dark#3119

Why not just post it here?
