### ISSUE TITLE
Status code 429

### ISSUE THREAD

**Issue by EvasiveXkiller** [fent/node-ytdl-core#968]
- If you're getting a specific error message, include the full stack trace
When trying to run this
```
ytdl.getInfo("https://www.youtube.com/watch?v=pRfmrE0ToTo").then((data) => {
    console.log(data.related_videos)
})
```
I get this

```
(node:10564) UnhandledPromiseRejectionWarning: Error: Status code: 429
    at ClientRequest.<anonymous> (E:\github\ytdldownloader\node_modules\miniget\dist\index.js:203:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)

```

Seems like youtube is being finicky again

**Comment by EvasiveXkiller** [comment]
Seems like this is related to #635 . Closing this
