### ISSUE TITLE
Some error while getting video details

### ISSUE THREAD

**Issue by cezarlacatus** [fent/node-ytdl-core#978]
(_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead [as _originalOnread] (internal/stream_base_commons.js:188:23)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:131:14) {
  statusCode: 429
}

Maybe it happens that I sended too many requests 5 hours ago?

**Comment by MatteZ02** [comment]
429 as in a ratelimit. That should go away within a few days max.
Alternatively you can try using a proxy or cookies to bypass it.

**Comment by cezarlacatus** [comment]
@MatteZ02 Do you know by  aproximation how many requests can I send?

**Comment by MatteZ02** [comment]
Unfortunately i don't. Youtube ratelimits are still a mystery

**Comment by cezarlacatus** [comment]
@MatteZ02 Thank you make for help me figure it out what is the error about.Take care
