### ISSUE TITLE
RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by LeGeek01** [fent/node-ytdl-core#990]
Hello, I have an error when my bot play a song in a voice channel.
RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at OpusScript.decode (/home/LeGeek01/SecretHeberg-Musique/node_modules/opusscript/index.js:78:17)
    at Decoder._decode (/home/LeGeek01/SecretHeberg-Musique/node_modules/prism-media/src/opus/Opus.js:64:25)
    at Decoder._transform (/home/LeGeek01/SecretHeberg-Musique/node_modules/prism-media/src/opus/Opus.js:204:22)
    at Decoder.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Decoder.Writable.write (node:internal/streams/writable:334:10)
    at PassThrough.ondata (node:internal/streams/readable:749:22)
    at PassThrough.emit (node:events:394:28)
I have :
- ytdl-core@4.9.1
- prism-media@1.3.2
- opusscript@0.0.8
- discord.js@12.5.3
- nodejs@16.6.1

Thanks in advance for answers.

**Comment by TimeForANinja** [comment]
the error stack points to `node_modules/opusscript/index.js:78:17` so try asking the opusscript devs 😉 
debugging a pipelin is kinda impossible
if you can recreate the error try going through it step by step:
* download to file using ytdl-core
* play from file with d.js

**Comment by LeGeek01** [comment]
Hello @TimeForANinja ,
Thanks you for your answer, I asking the opusscript.

**Comment by LeGeek01** [comment]
opusscript devs* (sorry)
